// ==========================================
// FANTASYPROS 2026 NFL DRAFT CONSENSUS RANKINGS
// Source: FantasyPros Expert Consensus
// Includes: Best, Worst, Average, Std Dev
// ==========================================

const fantasyProsBigBoardData = [
    { rank: 1, name: "Fernando Mendoza", position: "QB", school: "Indiana", tier: "Elite", avgRank: "3.0", bestRank: "1", worstRank: "5", stdDev: "1.7" },
    { rank: 2, name: "Arvell Reese", position: "LB", school: "Ohio State", tier: "Elite", avgRank: "3.4", bestRank: "1", worstRank: "5", stdDev: "1.6" },
    { rank: 3, name: "Caleb Downs", position: "S", school: "Ohio State", tier: "Elite", avgRank: "5.0", bestRank: "1", worstRank: "15", stdDev: "5.1" },
    { rank: 4, name: "Rueben Bain Jr.", position: "EDGE", school: "Miami", tier: "Elite", avgRank: "5.2", bestRank: "1", worstRank: "18", stdDev: "6.4" },
    { rank: 5, name: "Jeremiyah Love", position: "RB", school: "Notre Dame", tier: "Elite", avgRank: "5.4", bestRank: "2", worstRank: "10", stdDev: "3.4" },
    { rank: 6, name: "Francis Mauigoa", position: "OT", school: "Miami", tier: "Elite", avgRank: "8.0", bestRank: "6", worstRank: "13", stdDev: "2.6" },
    { rank: 7, name: "Mansoor Delane", position: "CB", school: "Virginia Tech", tier: "Elite", avgRank: "9.2", bestRank: "4", worstRank: "13", stdDev: "3.3" },
    { rank: 8, name: "Spencer Fano", position: "OT", school: "Utah", tier: "Elite", avgRank: "9.4", bestRank: "6", worstRank: "16", stdDev: "3.6" },
    { rank: 9, name: "David Bailey", position: "EDGE", school: "Texas Tech", tier: "Elite", avgRank: "9.6", bestRank: "3", worstRank: "19", stdDev: "5.5" },
    { rank: 10, name: "Jordyn Tyson", position: "WR", school: "Arizona State", tier: "Round 1", avgRank: "10.8", bestRank: "7", worstRank: "14", stdDev: "2.8" },
    { rank: 11, name: "Jermod McCoy", position: "CB", school: "Tennessee", tier: "Round 1", avgRank: "11.2", bestRank: "9", worstRank: "16", stdDev: "2.6" },
    { rank: 12, name: "Carnell Tate", position: "WR", school: "Ohio State", tier: "Round 1", avgRank: "12.4", bestRank: "5", worstRank: "20", stdDev: "5.5" },
    { rank: 13, name: "Sonny Styles", position: "LB", school: "Ohio State", tier: "Round 1", avgRank: "16.4", bestRank: "9", worstRank: "26", stdDev: "6.2" },
    { rank: 14, name: "Keldric Faulk", position: "EDGE", school: "Auburn", tier: "Round 1", avgRank: "17.4", bestRank: "7", worstRank: "42", stdDev: "12.9" },
    { rank: 15, name: "Peter Woods", position: "DT", school: "Clemson", tier: "Round 1", avgRank: "19.2", bestRank: "5", worstRank: "38", stdDev: "11.2" },
    { rank: 16, name: "Makai Lemon", position: "WR", school: "USC", tier: "Round 1", avgRank: "19.4", bestRank: "11", worstRank: "40", stdDev: "10.4" },
    { rank: 17, name: "Denzel Boston", position: "WR", school: "Washington", tier: "Round 1", avgRank: "20.0", bestRank: "12", worstRank: "25", stdDev: "4.4" },
    { rank: 18, name: "Avieon Terrell", position: "CB", school: "Clemson", tier: "Round 1", avgRank: "20.6", bestRank: "16", worstRank: "26", stdDev: "4.5" },
    { rank: 19, name: "Cashius Howell", position: "EDGE", school: "Texas A&M", tier: "Round 1", avgRank: "21.0", bestRank: "17", worstRank: "28", stdDev: "3.9" },
    { rank: 20, name: "Ty Simpson", position: "QB", school: "Alabama", tier: "Round 1", avgRank: "21.6", bestRank: "6", worstRank: "52", stdDev: "16.6" },
    { rank: 21, name: "Kenyon Sadiq", position: "TE", school: "Oregon", tier: "Round 1", avgRank: "22.2", bestRank: "10", worstRank: "38", stdDev: "9.3" },
    { rank: 22, name: "Olaivavega Ioane", position: "IOL", school: "Penn State", tier: "Round 1", avgRank: "23.2", bestRank: "18", worstRank: "31", stdDev: "4.8" },
    { rank: 23, name: "Caleb Lomu", position: "OT", school: "Utah", tier: "Round 1", avgRank: "24.8", bestRank: "19", worstRank: "30", stdDev: "3.7" },
    { rank: 24, name: "Kadyn Proctor", position: "OT", school: "Alabama", tier: "Round 1", avgRank: "25.0", bestRank: "17", worstRank: "44", stdDev: "9.7" },
    { rank: 25, name: "C.J. Allen", position: "LB", school: "Georgia", tier: "Round 1", avgRank: "26.6", bestRank: "23", worstRank: "30", stdDev: "2.4" },
    { rank: 26, name: "Brandon Cisse", position: "CB", school: "South Carolina", tier: "Round 1", avgRank: "27.8", bestRank: "14", worstRank: "35", stdDev: "7.3" },
    { rank: 27, name: "K.C. Concepcion", position: "WR", school: "Texas A&M", tier: "Round 1", avgRank: "28.4", bestRank: "21", worstRank: "40", stdDev: "7.3" },
    { rank: 28, name: "Akheem Mesidor (Miami", position: "DT", school: "FL", tier: "Round 2", avgRank: "32.2", bestRank: "18", worstRank: "54", stdDev: "13.2" },
    { rank: 29, name: "T.J. Parker", position: "EDGE", school: "Clemson", tier: "Round 2", avgRank: "34.4", bestRank: "17", worstRank: "80", stdDev: "23.0" },
    { rank: 30, name: "LT Overton", position: "DT", school: "Alabama", tier: "Round 2", avgRank: "34.4", bestRank: "23", worstRank: "50", stdDev: "10.5" },
    { rank: 31, name: "Dillon Thieneman", position: "S", school: "Oregon", tier: "Round 2", avgRank: "37.4", bestRank: "27", worstRank: "43", stdDev: "5.8" },
    { rank: 32, name: "Emmanuel Pregnon", position: "IOL", school: "Oregon", tier: "Round 2", avgRank: "37.8", bestRank: "32", worstRank: "49", stdDev: "6.7" },
    { rank: 33, name: "Anthony Hill Jr.", position: "LB", school: "Texas", tier: "Round 2", avgRank: "38.2", bestRank: "32", worstRank: "44", stdDev: "5.0" },
    { rank: 34, name: "R Mason Thomas", position: "EDGE", school: "Oklahoma", tier: "Round 2", avgRank: "39.8", bestRank: "25", worstRank: "58", stdDev: "10.9" },
    { rank: 35, name: "Chris Bell", position: "WR", school: "Louisville", tier: "Round 2", avgRank: "41.0", bestRank: "27", worstRank: "55", stdDev: "11.2" },
    { rank: 36, name: "Colton Hood", position: "CB", school: "Tennessee", tier: "Round 1", avgRank: "24.0", bestRank: "12", worstRank: "34", stdDev: "8.9" },
    { rank: 37, name: "Romello Height", position: "EDGE", school: "Texas Tech", tier: "Round 2", avgRank: "50.6", bestRank: "28", worstRank: "74", stdDev: "16.0" },
    { rank: 38, name: "Zion Young", position: "EDGE", school: "Missouri", tier: "Round 2", avgRank: "52.4", bestRank: "15", worstRank: "83", stdDev: "26.1" },
    { rank: 39, name: "Connor Lew", position: "IOL", school: "Auburn", tier: "Round 2", avgRank: "52.4", bestRank: "37", worstRank: "71", stdDev: "11.2" },
    { rank: 40, name: "Gabe Jacas", position: "EDGE", school: "Illinois", tier: "Round 2", avgRank: "52.8", bestRank: "30", worstRank: "80", stdDev: "17.9" },
    { rank: 41, name: "Kamari Ramsey", position: "S", school: "USC", tier: "Round 2", avgRank: "53.6", bestRank: "37", worstRank: "73", stdDev: "13.4" },
    { rank: 42, name: "Deontae Lawson", position: "LB", school: "Alabama", tier: "Round 2", avgRank: "55.6", bestRank: "43", worstRank: "81", stdDev: "13.6" },
    { rank: 43, name: "Keith Abney II", position: "CB", school: "Arizona State", tier: "Round 2", avgRank: "35.8", bestRank: "13", worstRank: "51", stdDev: "13.9" },
    { rank: 44, name: "Monroe Freeling", position: "OT", school: "Georgia", tier: "Round 2", avgRank: "37.0", bestRank: "28", worstRank: "62", stdDev: "14.4" },
    { rank: 45, name: "Jake Slaughter", position: "IOL", school: "Florida", tier: "Round 2", avgRank: "57.8", bestRank: "41", worstRank: "73", stdDev: "11.7" },
    { rank: 46, name: "Germie Bernard", position: "WR", school: "Alabama", tier: "Round 2", avgRank: "58.4", bestRank: "41", worstRank: "87", stdDev: "15.8" },
    { rank: 47, name: "Dani Dennis-Sutton ()", position: "EDGE", school: "Unknown", tier: "Round 2", avgRank: "60.8", bestRank: "29", worstRank: "83", stdDev: "17.9" },
    { rank: 48, name: "Lee Hunter", position: "DT", school: "Texas Tech", tier: "Round 2", avgRank: "62.2", bestRank: "30", worstRank: "83", stdDev: "20.6" },
    { rank: 49, name: "Emmanuel McNeil-Warren", position: "S", school: "Toledo", tier: "Round 2", avgRank: "43.5", bestRank: "21", worstRank: "79", stdDev: "21.5" },
    { rank: 50, name: "Ja'Kobi Lane", position: "WR", school: "USC", tier: "Round 2", avgRank: "63.0", bestRank: "32", worstRank: "116", stdDev: "28.4" },
    { rank: 51, name: "D'Angelo Ponds", position: "CB", school: "Indiana", tier: "Round 2", avgRank: "45.8", bestRank: "39", worstRank: "54", stdDev: "5.4" },
    { rank: 52, name: "Gennings Dunker", position: "OT", school: "Iowa", tier: "Round 2", avgRank: "47.0", bestRank: "34", worstRank: "67", stdDev: "12.2" },
    { rank: 53, name: "Chris Johnson", position: "CB", school: "San Diego State", tier: "Round 2", avgRank: "47.0", bestRank: "35", worstRank: "63", stdDev: "12.3" },
    { rank: 54, name: "Eli Stowers", position: "TE", school: "Vanderbilt", tier: "Round 2", avgRank: "48.8", bestRank: "36", worstRank: "72", stdDev: "14.3" },
    { rank: 55, name: "Max Klare", position: "TE", school: "Ohio State", tier: "Round 3", avgRank: "67.8", bestRank: "52", worstRank: "93", stdDev: "13.7" },
    { rank: 56, name: "Isaiah World", position: "OT", school: "Oregon", tier: "Round 3", avgRank: "68.0", bestRank: "37", worstRank: "126", stdDev: "32.7" },
    { rank: 57, name: "Harold Perkins Jr.", position: "LB", school: "LSU", tier: "Round 3", avgRank: "69.8", bestRank: "35", worstRank: "117", stdDev: "29.9" },
    { rank: 58, name: "A.J. Haulcy", position: "S", school: "LSU", tier: "Round 2", avgRank: "52.3", bestRank: "43", worstRank: "73", stdDev: "12.1" },
    { rank: 59, name: "Garrett Nussmeier", position: "QB", school: "LSU", tier: "Round 3", avgRank: "71.6", bestRank: "56", worstRank: "104", stdDev: "17.1" },
    { rank: 60, name: "Elijah Sarratt", position: "WR", school: "Indiana", tier: "Round 2", avgRank: "55.8", bestRank: "52", worstRank: "65", stdDev: "5.4" },
    { rank: 61, name: "Blake Miller", position: "OT", school: "Clemson", tier: "Round 2", avgRank: "57.0", bestRank: "47", worstRank: "78", stdDev: "12.5" },
    { rank: 62, name: "Joshua Josephs", position: "EDGE", school: "Tennessee", tier: "Round 2", avgRank: "59.0", bestRank: "40", worstRank: "81", stdDev: "14.6" },
    { rank: 63, name: "Caleb Tiernan", position: "OT", school: "Northwestern", tier: "Round 2", avgRank: "61.3", bestRank: "42", worstRank: "82", stdDev: "14.4" },
    { rank: 64, name: "Taurean York", position: "LB", school: "Texas A&M", tier: "Round 2", avgRank: "61.5", bestRank: "46", worstRank: "76", stdDev: "13.6" },
    { rank: 65, name: "Chris Brazzell II", position: "WR", school: "Tennessee", tier: "Round 2", avgRank: "62.5", bestRank: "44", worstRank: "75", stdDev: "11.8" },
    { rank: 66, name: "Drew Allar", position: "QB", school: "Penn State", tier: "Round 3", avgRank: "79.2", bestRank: "34", worstRank: "118", stdDev: "30.5" },
    { rank: 67, name: "Josiah Trotter", position: "LB", school: "Missouri", tier: "Round 3", avgRank: "65.0", bestRank: "57", worstRank: "77", stdDev: "7.4" },
    { rank: 68, name: "Zachariah Branch", position: "WR", school: "Georgia", tier: "Round 3", avgRank: "65.3", bestRank: "51", worstRank: "80", stdDev: "10.3" },
    { rank: 69, name: "Jake Golday ()", position: "LB", school: "Unknown", tier: "Round 3", avgRank: "67.0", bestRank: "59", worstRank: "86", stdDev: "11.0" },
    { rank: 70, name: "Derrick Moore", position: "EDGE", school: "Michigan", tier: "Round 3", avgRank: "69.5", bestRank: "56", worstRank: "86", stdDev: "12.1" },
    { rank: 71, name: "Malik Muhammad", position: "CB", school: "Texas", tier: "Round 3", avgRank: "70.5", bestRank: "52", worstRank: "99", stdDev: "17.4" },
    { rank: 72, name: "Antonio Williams", position: "WR", school: "Clemson", tier: "Round 3", avgRank: "71.0", bestRank: "51", worstRank: "91", stdDev: "14.1" },
    { rank: 73, name: "Dontay Corleone", position: "DT", school: "Cincinnati", tier: "Round 3", avgRank: "73.8", bestRank: "58", worstRank: "83", stdDev: "9.4" },
    { rank: 74, name: "Trinidad Chambliss", position: "QB", school: "Ole Miss", tier: "Round 2", avgRank: "52.3", bestRank: "32", worstRank: "67", stdDev: "14.8" },
    { rank: 75, name: "Davison Igbinosun", position: "CB", school: "Ohio State", tier: "Round 3", avgRank: "75.3", bestRank: "45", worstRank: "121", stdDev: "30.6" },
    { rank: 76, name: "Michael Trigg", position: "TE", school: "Baylor", tier: "Round 3", avgRank: "75.3", bestRank: "56", worstRank: "96", stdDev: "14.2" },
    { rank: 77, name: "Jadarian Price", position: "RB", school: "Notre Dame", tier: "Round 2", avgRank: "55.0", bestRank: "33", worstRank: "68", stdDev: "15.6" },
    { rank: 78, name: "Carson Beck", position: "QB", school: "Miami", tier: "Round 3", avgRank: "77.8", bestRank: "60", worstRank: "98", stdDev: "13.6" },
    { rank: 79, name: "Malachi Fields", position: "WR", school: "Notre Dame", tier: "Round 2", avgRank: "61.0", bestRank: "34", worstRank: "80", stdDev: "19.6" },
    { rank: 80, name: "Keionte Scott ()", position: "CB", school: "Unknown", tier: "Round 2", avgRank: "61.3", bestRank: "44", worstRank: "90", stdDev: "20.4" },
    { rank: 81, name: "Chase Bisontis", position: "IOL", school: "Texas A&M", tier: "Round 3", avgRank: "68.0", bestRank: "49", worstRank: "90", stdDev: "16.9" },
    { rank: 82, name: "Jonah Coleman", position: "RB", school: "Washington", tier: "Round 3", avgRank: "70.7", bestRank: "59", worstRank: "79", stdDev: "8.5" },
    { rank: 83, name: "Will Lee III ()", position: "CB", school: "Unknown", tier: "Round 3", avgRank: "71.3", bestRank: "29", worstRank: "103", stdDev: "31.1" },
    { rank: 84, name: "Deion Burks", position: "WR", school: "Oklahoma", tier: "Round 3", avgRank: "89.0", bestRank: "71", worstRank: "112", stdDev: "16.8" },
    { rank: 85, name: "Domani Jackson", position: "CB", school: "Alabama", tier: "Round 3", avgRank: "89.5", bestRank: "54", worstRank: "131", stdDev: "34.9" },
    { rank: 86, name: "Jack Endries", position: "TE", school: "Texas", tier: "Round 3", avgRank: "90.0", bestRank: "71", worstRank: "104", stdDev: "13.4" },
    { rank: 87, name: "Logan Jones", position: "C", school: "Iowa", tier: "Round 3", avgRank: "91.5", bestRank: "51", worstRank: "123", stdDev: "28.5" },
    { rank: 88, name: "Michael Taaffe", position: "S", school: "Texas", tier: "Round 3", avgRank: "92.3", bestRank: "67", worstRank: "123", stdDev: "24.3" },
    { rank: 89, name: "Austin Barber", position: "OT", school: "Florida", tier: "Round 3", avgRank: "80.3", bestRank: "48", worstRank: "106", stdDev: "24.1" },
    { rank: 90, name: "Nicholas Singleton", position: "RB", school: "Penn State", tier: "Round 3", avgRank: "82.7", bestRank: "66", worstRank: "101", stdDev: "14.3" },
    { rank: 91, name: "Kaytron Allen", position: "RB", school: "Penn State", tier: "Round 3", avgRank: "83.3", bestRank: "69", worstRank: "96", stdDev: "11.1" },
    { rank: 92, name: "Daylen Everette", position: "CB", school: "Georgia", tier: "Round 3", avgRank: "83.7", bestRank: "65", worstRank: "105", stdDev: "16.4" },
    { rank: 93, name: "Omar Cooper Jr.", position: "WR", school: "Indiana", tier: "Round 2", avgRank: "57.5", bestRank: "48", worstRank: "67", stdDev: "9.5" },
    { rank: 94, name: "Max Iheanachor ()", position: "OT", school: "Unknown", tier: "Round 2", avgRank: "59.0", bestRank: "40", worstRank: "78", stdDev: "19.0" },
    { rank: 95, name: "Zakee Wheatley ()", position: "S", school: "Unknown", tier: "Round 3", avgRank: "87.7", bestRank: "78", worstRank: "94", stdDev: "6.9" },
    { rank: 96, name: "Jaishawn Barham ()", position: "LB", school: "Unknown", tier: "Round 3", avgRank: "88.0", bestRank: "69", worstRank: "100", stdDev: "13.6" },
    { rank: 97, name: "Jude Bowry", position: "OT", school: "Boston College", tier: "Round 3", avgRank: "88.3", bestRank: "36", worstRank: "132", stdDev: "39.7" },
    { rank: 98, name: "Sam Hecht ()", position: "IOL", school: "Unknown", tier: "Round 3", avgRank: "67.0", bestRank: "52", worstRank: "82", stdDev: "15.0" },
    { rank: 99, name: "DeMonte Capehart", position: "DT", school: "Clemson", tier: "Round 3", avgRank: "93.3", bestRank: "69", worstRank: "124", stdDev: "22.9" },
    { rank: 100, name: "Drew Shelton", position: "OT", school: "Penn State", tier: "Round 3", avgRank: "93.7", bestRank: "55", worstRank: "136", stdDev: "33.2" },
    { rank: 101, name: "Mikail Kamara", position: "EDGE", school: "Indiana", tier: "Round 3", avgRank: "94.0", bestRank: "81", worstRank: "106", stdDev: "10.2" },
    { rank: 102, name: "Ar'maj Reed-Adams ()", position: "IOL", school: "Unknown", tier: "Round 3", avgRank: "95.7", bestRank: "54", worstRank: "119", stdDev: "29.5" },
    { rank: 103, name: "Emmett Johnson", position: "RB", school: "Nebraska", tier: "Round 3", avgRank: "75.0", bestRank: "66", worstRank: "84", stdDev: "9.0" },
    { rank: 104, name: "Julian Neal ()", position: "CB", school: "Unknown", tier: "Round 3", avgRank: "98.3", bestRank: "70", worstRank: "140", stdDev: "30.1" },
    { rank: 105, name: "Demond Claiborne", position: "RB", school: "Wake Forest", tier: "Round 3", avgRank: "99.0", bestRank: "68", worstRank: "115", stdDev: "21.9" },
    { rank: 106, name: "Caleb Banks", position: "DT", school: "Florida", tier: "Round 1", avgRank: "22.0", bestRank: "22", worstRank: "22", stdDev: "0.0" },
    { rank: 107, name: "Brian Parker II ()", position: "OT", school: "Unknown", tier: "Round 3", avgRank: "83.0", bestRank: "77", worstRank: "89", stdDev: "6.0" },
    { rank: 108, name: "Chandler Rivers", position: "CB", school: "Duke", tier: "Round 3", avgRank: "83.5", bestRank: "73", worstRank: "94", stdDev: "10.5" },
    { rank: 109, name: "Kayden McDonald", position: "DT", school: "Ohio State", tier: "Round 1", avgRank: "29.0", bestRank: "29", worstRank: "29", stdDev: "0.0" },
    { rank: 110, name: "Jacob Rodriguez ()", position: "LB", school: "Unknown", tier: "Round 3", avgRank: "86.0", bestRank: "70", worstRank: "102", stdDev: "16.0" },
    { rank: 111, name: "Jalon Kilgore", position: "S", school: "South Carolina", tier: "Round 3", avgRank: "106.7", bestRank: "73", worstRank: "148", stdDev: "31.1" },
    { rank: 112, name: "Christian Miller", position: "DT", school: "Georgia", tier: "Round 2", avgRank: "33.0", bestRank: "33", worstRank: "33", stdDev: "0.0" },
    { rank: 113, name: "Parker Brailsford", position: "IOL", school: "Alabama", tier: "Round 3", avgRank: "105.3", bestRank: "72", worstRank: "122", stdDev: "23.6" },
    { rank: 114, name: "Cade Klubnik", position: "QB", school: "Clemson", tier: "Round 3", avgRank: "105.7", bestRank: "48", worstRank: "140", stdDev: "41.0" },
    { rank: 115, name: "Keylan Rutledge ()", position: "IOL", school: "Unknown", tier: "Round 3", avgRank: "105.7", bestRank: "53", worstRank: "137", stdDev: "37.5" },
    { rank: 116, name: "Devin Moore ()", position: "CB", school: "Unknown", tier: "Round 3", avgRank: "111.0", bestRank: "88", worstRank: "154", stdDev: "30.4" },
    { rank: 117, name: "Skyler Bell", position: "WR", school: "Connecticut", tier: "Round 3", avgRank: "90.0", bestRank: "77", worstRank: "103", stdDev: "13.0" },
    { rank: 118, name: "Eli Raridon", position: "TE", school: "Notre Dame", tier: "Round 3", avgRank: "109.7", bestRank: "72", worstRank: "147", stdDev: "30.6" },
    { rank: 119, name: "Matt Gulbin ()", position: "IOL", school: "Unknown", tier: "Round 3", avgRank: "108.0", bestRank: "84", worstRank: "127", stdDev: "17.9" },
    { rank: 120, name: "Jaylon Guilbeau", position: "CB", school: "Texas", tier: "Round 3", avgRank: "92.0", bestRank: "49", worstRank: "135", stdDev: "43.0" },
    { rank: 121, name: "Beau Stephens ()", position: "IOL", school: "Unknown", tier: "Round 3", avgRank: "112.0", bestRank: "63", worstRank: "143", stdDev: "35.0" },
    { rank: 122, name: "Fernando Carmona ()", position: "IOL", school: "Unknown", tier: "Round 3", avgRank: "97.5", bestRank: "57", worstRank: "138", stdDev: "40.5" },
    { rank: 123, name: "Tacario Davis", position: "CB", school: "Arizona", tier: "Round 3", avgRank: "116.3", bestRank: "82", worstRank: "152", stdDev: "28.6" },
    { rank: 124, name: "Aaron Anderson", position: "WR", school: "LSU", tier: "Round 3", avgRank: "99.0", bestRank: "59", worstRank: "139", stdDev: "40.0" },
    { rank: 125, name: "Amare Ferrell", position: "S", school: "Indiana", tier: "Round 3", avgRank: "99.0", bestRank: "64", worstRank: "134", stdDev: "35.0" },
    { rank: 126, name: "C.J. Daniels", position: "WR", school: "Miami-FL", tier: "Round 3", avgRank: "100.0", bestRank: "88", worstRank: "112", stdDev: "12.0" },
    { rank: 127, name: "Keon Sabb", position: "S", school: "Alabama", tier: "Round 3", avgRank: "101.0", bestRank: "61", worstRank: "141", stdDev: "40.0" },
    { rank: 128, name: "Genesis Smith ()", position: "S", school: "Unknown", tier: "Round 3", avgRank: "101.5", bestRank: "92", worstRank: "111", stdDev: "9.5" },
    { rank: 129, name: "Jamari Johnson", position: "TE", school: "Oregon", tier: "Round 3", avgRank: "102.0", bestRank: "79", worstRank: "125", stdDev: "23.0" },
    { rank: 130, name: "Kyle Louis ()", position: "LB", school: "Unknown", tier: "Round 3", avgRank: "106.0", bestRank: "67", worstRank: "145", stdDev: "39.0" },
    { rank: 131, name: "D.J. Campbell", position: "IOL", school: "Texas", tier: "Round 3", avgRank: "116.7", bestRank: "85", worstRank: "137", stdDev: "22.7" },
    { rank: 132, name: "Xavier Scott", position: "CB", school: "Illinois", tier: "Round 3", avgRank: "105.0", bestRank: "102", worstRank: "108", stdDev: "3.0" },
    { rank: 133, name: "Earnest Greene III", position: "OT", school: "Georgia", tier: "Round 3", avgRank: "108.0", bestRank: "70", worstRank: "146", stdDev: "38.0" },
    { rank: 134, name: "Aamil Wagner ()", position: "OT", school: "Unknown", tier: "Round 3", avgRank: "121.3", bestRank: "82", worstRank: "153", stdDev: "29.5" },
    { rank: 135, name: "Domonique Orange", position: "DT", school: "Iowa State", tier: "Round 3", avgRank: "72.0", bestRank: "72", worstRank: "72", stdDev: "0.0" },
    { rank: 136, name: "Caden Curry ()", position: "EDGE", school: "Unknown", tier: "Round 3", avgRank: "122.7", bestRank: "88", worstRank: "155", stdDev: "27.4" },
    { rank: 137, name: "John Michael Gyllenborg", position: "TE", school: "Wyoming", tier: "Round 3", avgRank: "112.0", bestRank: "75", worstRank: "149", stdDev: "37.0" },
    { rank: 138, name: "Bud Clark ()", position: "S", school: "Unknown", tier: "Round 3", avgRank: "76.0", bestRank: "76", worstRank: "76", stdDev: "0.0" },
    { rank: 139, name: "Diego Pounds ()", position: "OT", school: "Unknown", tier: "Round 3", avgRank: "114.0", bestRank: "78", worstRank: "150", stdDev: "36.0" },
    { rank: 140, name: "Darrell Jackson Jr.", position: "DT", school: "Florida State", tier: "Round 3", avgRank: "84.0", bestRank: "84", worstRank: "84", stdDev: "0.0" },
    { rank: 141, name: "Anthony Lucas", position: "EDGE", school: "USC", tier: "Round 3", avgRank: "86.0", bestRank: "86", worstRank: "86", stdDev: "0.0" },
    { rank: 142, name: "Patrick Payton", position: "DT", school: "Florida State", tier: "Round 3", avgRank: "89.0", bestRank: "89", worstRank: "89", stdDev: "0.0" },
    { rank: 143, name: "Justin Joly", position: "TE", school: "NC State", tier: "Round 3", avgRank: "116.0", bestRank: "108", worstRank: "124", stdDev: "8.0" },
    { rank: 144, name: "J.C. Davis", position: "OT", school: "Illinois", tier: "Round 3", avgRank: "92.0", bestRank: "92", worstRank: "92", stdDev: "0.0" },
    { rank: 145, name: "Treydan Stukes ()", position: "CB", school: "Unknown", tier: "Round 3", avgRank: "124.5", bestRank: "93", worstRank: "156", stdDev: "31.5" },
    { rank: 146, name: "Tyreak Sapp", position: "EDGE", school: "Florida", tier: "Round 3", avgRank: "97.0", bestRank: "97", worstRank: "97", stdDev: "0.0" },
    { rank: 147, name: "Lander Barton", position: "LB", school: "Utah", tier: "Round 3", avgRank: "128.5", bestRank: "100", worstRank: "157", stdDev: "28.5" },
    { rank: 148, name: "Skyler Gill-Howard ()", position: "DT", school: "Unknown", tier: "Round 3", avgRank: "122.5", bestRank: "107", worstRank: "138", stdDev: "15.5" },
    { rank: 149, name: "Seth McGowan", position: "RB", school: "Kentucky", tier: "Round 3", avgRank: "105.0", bestRank: "105", worstRank: "105", stdDev: "0.0" },
    { rank: 150, name: "Eric McAlister", position: "WR", school: "TCU", tier: "Round 3", avgRank: "109.0", bestRank: "109", worstRank: "109", stdDev: "0.0" },
    { rank: 151, name: "Sam Roush", position: "TE", school: "Stanford", tier: "Round 3", avgRank: "110.0", bestRank: "110", worstRank: "110", stdDev: "0.0" },
    { rank: 152, name: "Ted Hurst", position: "WR", school: "Georgia State", tier: "Round 3", avgRank: "134.5", bestRank: "111", worstRank: "158", stdDev: "23.5" },
    { rank: 153, name: "Malachi Lawrence ()", position: "EDGE", school: "Unknown", tier: "Round 3", avgRank: "137.5", bestRank: "116", worstRank: "159", stdDev: "21.5" },
    { rank: 154, name: "Louis Moore ()", position: "S", school: "Unknown", tier: "Round 3", avgRank: "131.0", bestRank: "118", worstRank: "144", stdDev: "13.0" },
    { rank: 155, name: "J'Mari Taylor", position: "RB", school: "Virginia", tier: "Round 3", avgRank: "119.0", bestRank: "119", worstRank: "119", stdDev: "0.0" },
    { rank: 156, name: "Roman Hemby", position: "RB", school: "Indiana", tier: "Round 3", avgRank: "120.0", bestRank: "120", worstRank: "120", stdDev: "0.0" },
    { rank: 157, name: "Oscar Delp", position: "TE", school: "Georgia", tier: "Round 3", avgRank: "140.0", bestRank: "120", worstRank: "160", stdDev: "20.0" },
    { rank: 158, name: "Joe Royer", position: "TE", school: "Cincinnati", tier: "Round 3", avgRank: "141.0", bestRank: "121", worstRank: "161", stdDev: "20.0" },
    { rank: 159, name: "Hezekiah Masses ()", position: "CB", school: "Unknown", tier: "Round 3", avgRank: "144.0", bestRank: "126", worstRank: "162", stdDev: "18.0" },
    { rank: 160, name: "Brenen Thompson", position: "WR", school: "Mississippi State", tier: "Round 3", avgRank: "145.5", bestRank: "128", worstRank: "163", stdDev: "17.5" },
    { rank: 161, name: "Le'Veon Moss", position: "RB", school: "Texas A&M", tier: "Round 3", avgRank: "130.0", bestRank: "130", worstRank: "130", stdDev: "0.0" },
    { rank: 162, name: "Eric Rivers", position: "WR", school: "Georgia Tech", tier: "Round 3", avgRank: "147.5", bestRank: "131", worstRank: "164", stdDev: "16.5" },
    { rank: 163, name: "Kage Casey ()", position: "OT", school: "Unknown", tier: "Round 3", avgRank: "148.5", bestRank: "132", worstRank: "165", stdDev: "16.5" },
    { rank: 164, name: "Ahmad Moten Sr. ()", position: "DT", school: "Unknown", tier: "Round 3", avgRank: "133.0", bestRank: "133", worstRank: "133", stdDev: "0.0" },
    { rank: 165, name: "Albert Regis ()", position: "DT", school: "Unknown", tier: "Round 3", avgRank: "149.5", bestRank: "133", worstRank: "166", stdDev: "16.5" },
    { rank: 166, name: "Gracen Halton ()", position: "DT", school: "Unknown", tier: "Round 3", avgRank: "150.5", bestRank: "134", worstRank: "167", stdDev: "16.5" },
    { rank: 167, name: "Kevin Coleman Jr.", position: "WR", school: "Missouri", tier: "Round 3", avgRank: "143.0", bestRank: "135", worstRank: "151", stdDev: "8.0" },
    { rank: 168, name: "Aiden Fisher ()", position: "LB", school: "Unknown", tier: "Round 3", avgRank: "152.0", bestRank: "136", worstRank: "168", stdDev: "16.0" },
    { rank: 169, name: "Dallen Bentley", position: "TE", school: "Utah", tier: "Round 3", avgRank: "154.0", bestRank: "139", worstRank: "169", stdDev: "15.0" },
    { rank: 170, name: "Bishop Fitzgerald ()", position: "S", school: "Unknown", tier: "Round 3", avgRank: "142.0", bestRank: "142", worstRank: "142", stdDev: "0.0" },
    { rank: 171, name: "Mike Washington Jr.", position: "RB", school: "Arkansas", tier: "Round 3", avgRank: "170.0", bestRank: "170", worstRank: "170", stdDev: "0.0" },
    { rank: 172, name: "Adam Randall", position: "RB", school: "Clemson", tier: "Round 3", avgRank: "171.0", bestRank: "171", worstRank: "171", stdDev: "0.0" },
    { rank: 173, name: "Chip Trayanum", position: "RB", school: "Toledo", tier: "Round 3", avgRank: "172.0", bestRank: "172", worstRank: "172", stdDev: "0.0" },
    { rank: 174, name: "Desmond Reid", position: "RB", school: "Pittsburgh", tier: "Round 3", avgRank: "173.0", bestRank: "173", worstRank: "173", stdDev: "0.0" },
    { rank: 175, name: "Jaydn Ott", position: "RB", school: "California", tier: "Round 3", avgRank: "174.0", bestRank: "174", worstRank: "174", stdDev: "0.0" },
    { rank: 176, name: "Kaelon Black", position: "RB", school: "Indiana", tier: "Round 3", avgRank: "175.0", bestRank: "175", worstRank: "175", stdDev: "0.0" },
    { rank: 177, name: "Rahsul Faison", position: "RB", school: "South Carolina", tier: "Round 3", avgRank: "176.0", bestRank: "176", worstRank: "176", stdDev: "0.0" }
];

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { fantasyProsBigBoardData };
}