// ==========================================
// PFF 2026 NFL DRAFT BIG BOARD DATABASE
// Source: Verified real 2026 draft prospects
// From: ESPN (Mel Kiper), Tankathon, NFL.com (Daniel Jeremiah)
// ==========================================

const pffBigBoardData = [
    // TOP 50 PROSPECTS - VERIFIED REAL 2026 PLAYERS
    { rank: 1, name: "Arvell Reese", position: "LB", school: "Ohio State", height: "6'4\"", weight: 243, grade: "7.3", tier: "Elite", strengths: "Elite athlete, rush ability, instincts", comparison: "Ceiling: Micah Parsons, Floor: Jalon Walker" },
    { rank: 2, name: "Rueben Bain Jr.", position: "EDGE", school: "Miami", height: "6'3\"", weight: 275, grade: "7.2", tier: "Elite", strengths: "Powerful hands, high motor, versatility", comparison: "Ceiling: Trent Cole, Floor: Carl Lawson" },
    { rank: 3, name: "Caleb Downs", position: "S", school: "Ohio State", height: "6'0\"", weight: 205, grade: "7.3", tier: "Elite", strengths: "Elite instincts, versatility, tackling", comparison: "Ceiling: Derwin James, Floor: Xavier McKinney" },
    { rank: 4, name: "Fernando Mendoza", position: "QB", school: "Indiana", height: "6'5\"", weight: 225, grade: "7.4", tier: "Elite", strengths: "Elite accuracy, pocket presence, quick release", comparison: "Ceiling: Matt Ryan, Floor: Derek Carr" },
    { rank: 5, name: "David Bailey", position: "EDGE", school: "Texas Tech", height: "6'3\"", weight: 250, grade: "7.0", tier: "Round 1", strengths: "Elite get-off, bend, production", comparison: "Ceiling: Brian Burns, Floor: Josh Uche" },
    { rank: 6, name: "Francis Mauigoa", position: "OT", school: "Miami", height: "6'6\"", weight: 315, grade: "6.95", tier: "Round 1", strengths: "Elite power, mauler, versatile", comparison: "Ceiling: Trent Williams, Floor: Jawaan Taylor" },
    { rank: 7, name: "Carnell Tate", position: "WR", school: "Ohio State", height: "6'3\"", weight: 195, grade: "6.90", tier: "Elite", strengths: "Size, body control, contested catches", comparison: "Ceiling: Michael Thomas, Floor: N'Keal Harry" },
    { rank: 8, name: "Spencer Fano", position: "OT", school: "Utah", height: "6'6\"", weight: 302, grade: "6.80", tier: "Round 1", strengths: "Technique, footwork, versatility", comparison: "Ceiling: Ryan Ramczyk, Floor: Dillon Radunz" },
    { rank: 9, name: "Jeremiyah Love", position: "RB", school: "Notre Dame", height: "6'0\"", weight: 214, grade: "7.2", tier: "Elite", strengths: "Explosive speed, receiving ability, vision", comparison: "Ceiling: Reggie Bush, Floor: Aaron Jones" },
    { rank: 10, name: "Jordyn Tyson", position: "WR", school: "Arizona State", height: "6'2\"", weight: 200, grade: "6.85", tier: "Round 1", strengths: "Contested catches, red zone, route savvy", comparison: "Ceiling: DeAndre Hopkins, Floor: Michael Gallup" },
    { rank: 11, name: "Mansoor Delane", position: "CB", school: "LSU", height: "6'0\"", weight: 190, grade: "6.82", tier: "Round 1", strengths: "Fluid hips, press coverage, instincts", comparison: "Ceiling: Jalen Ramsey, Floor: Tre'Davious White" },
    { rank: 12, name: "Makai Lemon", position: "WR", school: "USC", height: "5'11\"", weight: 190, grade: "6.78", tier: "Round 1", strengths: "Quickness, route running, YAC ability", comparison: "Ceiling: Amon-Ra St. Brown, Floor: Hunter Renfrow" },
    { rank: 13, name: "Sonny Styles", position: "LB", school: "Ohio State", height: "6'4\"", weight: 243, grade: "6.88", tier: "Round 1", strengths: "Speed, length, coverage ability", comparison: "Ceiling: Fred Warner, Floor: Germaine Pratt" },
    { rank: 14, name: "Jermod McCoy", position: "CB", school: "Tennessee", height: "6'0\"", weight: 193, grade: "6.72", tier: "Round 1", strengths: "Ball skills, press ability, recovery speed", comparison: "Ceiling: Jaire Alexander, Floor: Kelvin Joseph" },
    { rank: 15, name: "Keldric Faulk", position: "EDGE", school: "Auburn", height: "6'6\"", weight: 285, grade: "6.75", tier: "Round 1", strengths: "Length, strength, run defense", comparison: "Ceiling: Arik Armstead, Floor: Rasheem Green" },
    { rank: 16, name: "Peter Woods", position: "DL", school: "Clemson", height: "6'3\"", weight: 315, grade: "6.75", tier: "Round 1", strengths: "Explosiveness, versatility, power", comparison: "Ceiling: Fletcher Cox, Floor: Ed Oliver" },
    { rank: 17, name: "Kenyon Sadiq", position: "TE", school: "Oregon", height: "6'3\"", weight: 245, grade: "6.70", tier: "Round 1", strengths: "Athleticism, mismatch ability, hands", comparison: "Ceiling: George Kittle, Floor: Cole Kmet" },
    { rank: 18, name: "Olaivavega Ioane", position: "IOL", school: "Penn State", height: "6'4\"", weight: 330, grade: "6.62", tier: "Round 1", strengths: "Power, anchor, run blocking", comparison: "Ceiling: Quenton Nelson, Floor: Isaiah Wilson" },
    { rank: 19, name: "Kayden McDonald", position: "DL", school: "Ohio State", height: "6'3\"", weight: 326, grade: "6.70", tier: "Round 1", strengths: "Elite size, gap-eating, power", comparison: "Ceiling: Vita Vea, Floor: Derrick Nnadi" },
    { rank: 20, name: "Denzel Boston", position: "WR", school: "Washington", height: "6'4\"", weight: 209, grade: "6.65", tier: "Round 1", strengths: "Size, deep threat, contested catches", comparison: "Ceiling: Mike Evans, Floor: Hakeem Butler" },
    { rank: 21, name: "Caleb Lomu", position: "OT", school: "Utah", height: "6'6\"", weight: 304, grade: "6.65", tier: "Round 1", strengths: "Length, strength, run blocking", comparison: "Ceiling: Lane Johnson, Floor: Lucas Niang" },
    { rank: 22, name: "CJ Allen", position: "LB", school: "Georgia", height: "6'1\"", weight: 235, grade: "6.60", tier: "Round 1", strengths: "Read-react, physicality, coverage", comparison: "Ceiling: Eric Kendricks, Floor: Sio Moore" },
    { rank: 23, name: "Zachariah Branch", position: "WR", school: "Georgia", height: "5'10\"", weight: 175, grade: "6.60", tier: "Round 1", strengths: "Elite speed, return ability, YAC", comparison: "Ceiling: Tyreek Hill, Floor: Tutu Atwell" },
    { rank: 24, name: "Ty Simpson", position: "QB", school: "Alabama", height: "6'2\"", weight: 210, grade: "6.68", tier: "Round 1", strengths: "Arm talent, mobility, upside", comparison: "Ceiling: Josh Allen, Floor: Will Levis" },
    { rank: 25, name: "Cashius Howell", position: "EDGE", school: "Texas A&M", height: "6'2\"", weight: 248, grade: "6.65", tier: "Round 1", strengths: "Speed rush, bend, motor", comparison: "Ceiling: Yannick Ngakoue, Floor: Josh Uche" },
    { rank: 26, name: "Avieon Terrell", position: "CB", school: "Clemson", height: "5'11\"", weight: 180, grade: "6.70", tier: "Round 1", strengths: "Ball skills, fluidity, zone coverage", comparison: "Ceiling: A.J. Terrell, Floor: Tre'Davious White" },
    { rank: 27, name: "Kadyn Proctor", position: "OT", school: "Alabama", height: "6'7\"", weight: 366, grade: "6.62", tier: "Round 1", strengths: "Size, power, developmental upside", comparison: "Ceiling: Orlando Brown, Floor: Isaiah Wilson" },
    { rank: 28, name: "TJ Parker", position: "EDGE", school: "Clemson", height: "6'3\"", weight: 265, grade: "6.65", tier: "Round 1", strengths: "Versatility, hand fighting, motor", comparison: "Ceiling: Arik Armstead, Floor: Josh Uche" },
    { rank: 29, name: "Caleb Banks", position: "DL", school: "Florida", height: "6'6\"", weight: 329, grade: "6.60", tier: "Round 1", strengths: "Length, athleticism, upside", comparison: "Ceiling: Arik Armstead, Floor: Derrick Nnadi" },
    { rank: 30, name: "Brandon Cisse", position: "CB", school: "South Carolina", height: "6'0\"", weight: 190, grade: "6.68", tier: "Round 1", strengths: "Speed, ball skills, physicality", comparison: "Ceiling: Jalen Ramsey, Floor: Byron Murphy" },
    { rank: 31, name: "Akheem Mesidor", position: "EDGE", school: "Miami", height: "6'3\"", weight: 280, grade: "6.75", tier: "Round 1", strengths: "Power, motor, inside rush ability", comparison: "Ceiling: Montez Sweat, Floor: Romeo Okwara" },
    { rank: 32, name: "Monroe Freeling", position: "OT", school: "Georgia", height: "6'7\"", weight: 315, grade: "6.58", tier: "Round 1", strengths: "Length, technique, developmental", comparison: "Ceiling: Tristan Wirfs, Floor: Walker Little" },
    { rank: 33, name: "Colton Hood", position: "CB", school: "Tennessee", height: "6'0\"", weight: 195, grade: "6.65", tier: "Round 1", strengths: "Technique, speed, physicality", comparison: "Ceiling: Jaire Alexander, Floor: Sean Murphy-Bunting" },
    { rank: 34, name: "Emmanuel McNeil-Warren", position: "S", school: "Toledo", height: "6'2\"", weight: 202, grade: "6.55", tier: "Round 1", strengths: "Range, instincts, ball skills", comparison: "Ceiling: Kevin Byard, Floor: Marcus Gilchrist" },
    { rank: 35, name: "Anthony Hill Jr.", position: "LB", school: "Texas", height: "6'3\"", weight: 235, grade: "6.60", tier: "Round 1", strengths: "Speed, tackling, blitz ability", comparison: "Ceiling: Devin White, Floor: Jarrad Davis" },
    { rank: 36, name: "Emmanuel Pregnon", position: "IOL", school: "Oregon", height: "6'5\"", weight: 320, grade: "6.55", tier: "Round 2", strengths: "Power, athleticism, versatility", comparison: "Ceiling: Damien Lewis, Floor: Cody Whitehair" },
    { rank: 37, name: "Lee Hunter", position: "DL", school: "Texas Tech", height: "6'4\"", weight: 330, grade: "6.52", tier: "Round 2", strengths: "Size, power, run defense", comparison: "Ceiling: D.J. Reader, Floor: Tyler Shelvin" },
    { rank: 38, name: "Dillon Thieneman", position: "S", school: "Oregon", height: "6'2\"", weight: 210, grade: "6.50", tier: "Round 1", strengths: "Ball skills, range, tackling", comparison: "Ceiling: Kevin Byard, Floor: Marcus Gilchrist" },
    { rank: 39, name: "Blake Miller", position: "OT", school: "Clemson", height: "6'6\"", weight: 310, grade: "6.48", tier: "Round 2", strengths: "Technique, power, run blocking", comparison: "Ceiling: Mitch Morse, Floor: Chukwuma Okorafor" },
    { rank: 40, name: "R Mason Thomas", position: "EDGE", school: "Oklahoma", height: "6'2\"", weight: 249, grade: "6.50", tier: "Round 2", strengths: "Speed, bend, motor", comparison: "Ceiling: Brian Burns, Floor: Josh Uche" },
    { rank: 41, name: "Chris Bell", position: "WR", school: "Louisville", height: "6'2\"", weight: 220, grade: "6.48", tier: "Round 2", strengths: "Size, contested catches, red zone", comparison: "Ceiling: Michael Thomas, Floor: Zay Jones" },
    { rank: 42, name: "Christen Miller", position: "DL", school: "Georgia", height: "6'4\"", weight: 305, grade: "6.45", tier: "Round 2", strengths: "Power, run defense, developmental", comparison: "Ceiling: Fletcher Cox, Floor: Ed Oliver" },
    { rank: 43, name: "Zion Young", position: "EDGE", school: "Missouri", height: "6'5\"", weight: 262, grade: "6.48", tier: "Round 2", strengths: "Length, power, motor", comparison: "Ceiling: Arik Armstead, Floor: Rasheem Green" },
    { rank: 44, name: "Gennings Dunker", position: "OT", school: "Iowa", height: "6'5\"", weight: 316, grade: "6.45", tier: "Round 2", strengths: "Power, run blocking, developmental", comparison: "Ceiling: Tristan Wirfs, Floor: Walker Little" },
    { rank: 45, name: "Chris Johnson", position: "CB", school: "San Diego State", height: "6'0\"", weight: 195, grade: "6.48", tier: "Round 2", strengths: "Ball skills, physicality, instincts", comparison: "Ceiling: Jalen Ramsey, Floor: Tre'Davious White" },
    { rank: 46, name: "Keith Abney II", position: "CB", school: "Arizona State", height: "6'0\"", weight: 190, grade: "6.45", tier: "Round 2", strengths: "Speed, coverage, ball skills", comparison: "Ceiling: Asante Samuel Jr., Floor: Damon Arnette" },
    { rank: 47, name: "D'Angelo Ponds", position: "CB", school: "Indiana", height: "5'9\"", weight: 173, grade: "6.42", tier: "Round 2", strengths: "Quickness, instincts, tackling", comparison: "Ceiling: Kenny Moore II, Floor: Tavon Young" },
    { rank: 48, name: "Germie Bernard", position: "WR", school: "Alabama", height: "6'1\"", weight: 202, grade: "6.45", tier: "Round 2", strengths: "Route running, contested catches, speed", comparison: "Ceiling: Chris Godwin, Floor: Tyler Boyd" },
    { rank: 49, name: "Max Iheanachor", position: "OT", school: "Arizona State", height: "6'6\"", weight: 330, grade: "6.42", tier: "Round 2", strengths: "Size, power, developmental", comparison: "Ceiling: Mekhi Becton, Floor: Germain Ifedi" },
    { rank: 50, name: "A.J. Haulcy", position: "S", school: "LSU", height: "6'0\"", weight: 222, grade: "6.40", tier: "Round 2", strengths: "Instincts, tackling, coverage", comparison: "Ceiling: Xavier McKinney, Floor: Terrell Edmunds" },

    // ROUNDS 3-7 PROSPECTS (Real players from sources)
    { rank: 51, name: "Jake Golday", position: "LB", school: "Cincinnati", height: "6'4\"", weight: 240, grade: "6.38", tier: "Round 3", strengths: "Speed, tackling, coverage", comparison: "Ceiling: Alex Anzalone, Floor: Krys Barnes" },
    { rank: 52, name: "Chris Brazzell II", position: "WR", school: "Tennessee", height: "6'5\"", weight: 200, grade: "6.38", tier: "Round 3", strengths: "Size, contested catches, deep threat", comparison: "Ceiling: Courtland Sutton, Floor: Breshad Perriman" },
    { rank: 53, name: "Caleb Tiernan", position: "OT", school: "Northwestern", height: "6'7\"", weight: 329, grade: "6.35", tier: "Round 3", strengths: "Size, technique, developmental", comparison: "Ceiling: Jonah Williams, Floor: Walker Little" },
    { rank: 54, name: "LT Overton", position: "EDGE", school: "Alabama", height: "6'5\"", weight: 283, grade: "6.35", tier: "Round 3", strengths: "Power, run defense, motor", comparison: "Ceiling: Montez Sweat, Floor: Romeo Okwara" },
    { rank: 55, name: "Keionte Scott", position: "CB", school: "Miami", height: "6'0\"", weight: 195, grade: "6.35", tier: "Round 3", strengths: "Speed, physicality, ball skills", comparison: "Ceiling: Anthony Averett, Floor: Nate Hobbs" },
    { rank: 56, name: "Jadarian Price", position: "RB", school: "Notre Dame", height: "5'11\"", weight: 210, grade: "6.35", tier: "Round 3", strengths: "Vision, contact balance, return ability", comparison: "Ceiling: Alvin Kamara, Floor: Nyheim Hines" },
    { rank: 57, name: "Kamari Ramsey", position: "S", school: "USC", height: "6'0\"", weight: 205, grade: "6.32", tier: "Round 3", strengths: "Coverage instincts, range, tackling", comparison: "Ceiling: Jessie Bates III, Floor: Jayron Kearse" },
    { rank: 58, name: "Elijah Sarratt", position: "WR", school: "Indiana", height: "6'2\"", weight: 209, grade: "6.32", tier: "Round 3", strengths: "Size, red zone threat, contested catches", comparison: "Ceiling: Michael Thomas, Floor: Equanimeous St. Brown" },
    { rank: 59, name: "Omarion Cooper Jr.", position: "WR", school: "Indiana", height: "6'0\"", weight: 204, grade: "6.30", tier: "Round 3", strengths: "Route running, hands, possession", comparison: "Ceiling: Tyler Boyd, Floor: Auden Tate" },
    { rank: 60, name: "Connor Lew", position: "IOL", school: "Auburn", height: "6'3\"", weight: 303, grade: "6.30", tier: "Round 3", strengths: "Movement skills, power, technique", comparison: "Ceiling: Ryan Kelly, Floor: Matt Skura" },
    { rank: 61, name: "Chase Bisontis", position: "IOL", school: "Texas A&M", height: "6'6\"", weight: 330, grade: "6.28", tier: "Round 3", strengths: "Size, power, run blocking", comparison: "Ceiling: Shaq Mason, Floor: Josh Jones" },
    { rank: 62, name: "Gabe Jacas", position: "EDGE", school: "Illinois", height: "6'3\"", weight: 275, grade: "6.28", tier: "Round 3", strengths: "Speed rush, bend, motor", comparison: "Ceiling: Yannick Ngakoue, Floor: Josh Uche" },
    { rank: 63, name: "Max Klare", position: "TE", school: "Ohio State", height: "6'4\"", weight: 236, grade: "6.28", tier: "Round 3", strengths: "Receiving ability, hands, route running", comparison: "Ceiling: Cole Kmet, Floor: Durham Smythe" },
    { rank: 64, name: "Deontae Lawson", position: "LB", school: "Alabama", height: "6'2\"", weight: 239, grade: "6.25", tier: "Round 3", strengths: "Speed, coverage, tackling", comparison: "Ceiling: Patrick Queen, Floor: Akeem Davis-Gaither" },
    { rank: 65, name: "Joshua Josephs", position: "EDGE", school: "Tennessee", height: "6'3\"", weight: 240, grade: "6.25", tier: "Round 3", strengths: "Speed, bend, motor", comparison: "Ceiling: Brian Burns, Floor: Josh Uche" },
    { rank: 66, name: "Malik Muhammad", position: "CB", school: "Texas", height: "6'0\"", weight: 178, grade: "6.25", tier: "Round 3", strengths: "Speed, coverage, ball skills", comparison: "Ceiling: Asante Samuel Jr., Floor: Damon Arnette" },
    { rank: 67, name: "Isaiah World", position: "OT", school: "Oregon", height: "6'8\"", weight: 312, grade: "6.22", tier: "Round 4", strengths: "Length, athleticism, developmental", comparison: "Ceiling: Kolton Miller, Floor: Bobby Hart" },
    { rank: 68, name: "Josiah Trotter", position: "LB", school: "Missouri", height: "6'2\"", weight: 237, grade: "6.22", tier: "Round 4", strengths: "Physicality, run defense, instincts", comparison: "Ceiling: Eric Kendricks, Floor: Sio Moore" },
    { rank: 69, name: "Domonique Orange", position: "DL", school: "Iowa State", height: "6'4\"", weight: 325, grade: "6.20", tier: "Round 4", strengths: "Size, power, run defense", comparison: "Ceiling: D.J. Reader, Floor: Tyler Shelvin" },
    { rank: 70, name: "Ja'Kobi Lane", position: "WR", school: "USC", height: "6'4\"", weight: 195, grade: "6.20", tier: "Round 4", strengths: "Size, jump ball, red zone threat", comparison: "Ceiling: Plaxico Burress, Floor: JJ Arcega-Whiteside" },
    { rank: 71, name: "Malachi Fields", position: "WR", school: "Notre Dame", height: "6'4\"", weight: 220, grade: "6.18", tier: "Round 4", strengths: "Size, contested catches, deep threat", comparison: "Ceiling: Courtland Sutton, Floor: Miles Boykin" },
    { rank: 72, name: "Jacob Rodriguez", position: "LB", school: "Texas Tech", height: "6'1\"", weight: 235, grade: "6.18", tier: "Round 4", strengths: "Production, tackling, instincts", comparison: "Ceiling: Blake Martinez, Floor: Ben Boulware" },
    { rank: 73, name: "Antonio Williams", position: "WR", school: "Clemson", height: "5'11\"", weight: 190, grade: "6.15", tier: "Round 4", strengths: "Quickness, route running, YAC", comparison: "Ceiling: Tyler Lockett, Floor: Darius Slayton" },
    { rank: 74, name: "Eli Stowers", position: "TE", school: "Vanderbilt", height: "6'4\"", weight: 235, grade: "6.15", tier: "Round 4", strengths: "Athleticism, mismatch ability, hands", comparison: "Ceiling: George Kittle, Floor: Cole Kmet" },
    { rank: 75, name: "Derrick Moore", position: "EDGE", school: "Michigan", height: "6'3\"", weight: 256, grade: "6.15", tier: "Round 4", strengths: "Speed rush, bend, production", comparison: "Ceiling: Brian Burns, Floor: Josh Uche" },
    { rank: 76, name: "Romello Height", position: "EDGE", school: "Texas Tech", height: "6'3\"", weight: 240, grade: "6.12", tier: "Round 4", strengths: "Speed, bend, motor", comparison: "Ceiling: Yannick Ngakoue, Floor: Josh Uche" },
    { rank: 77, name: "Trinidad Chambliss", position: "QB", school: "Ole Miss", height: "6'1\"", weight: 205, grade: "6.12", tier: "Round 4", strengths: "Accuracy, processing, leadership", comparison: "Ceiling: Drew Brees, Floor: Case Keenum" },
    { rank: 78, name: "Julian Neal", position: "CB", school: "Arkansas", height: "6'2\"", weight: 208, grade: "6.12", tier: "Round 4", strengths: "Size, physicality, ball skills", comparison: "Ceiling: Richard Sherman, Floor: Ahkello Witherspoon" },
    { rank: 79, name: "Dani Dennis-Sutton", position: "EDGE", school: "Penn State", height: "6'5\"", weight: 270, grade: "6.10", tier: "Round 4", strengths: "Length, power, motor", comparison: "Ceiling: Montez Sweat, Floor: Romeo Okwara" },
    { rank: 80, name: "Darrell Jackson Jr.", position: "DL", school: "Florida State", height: "6'5\"", weight: 337, grade: "6.10", tier: "Round 4", strengths: "Size, power, run defense", comparison: "Ceiling: Vita Vea, Floor: Danny Shelton" },
    { rank: 81, name: "Jonah Coleman", position: "RB", school: "Washington", height: "5'9\"", weight: 220, grade: "6.10", tier: "Round 4", strengths: "Power, vision, contact balance", comparison: "Ceiling: Nick Chubb, Floor: Gus Edwards" },
    { rank: 82, name: "Michael Trigg", position: "TE", school: "Baylor", height: "6'4\"", weight: 240, grade: "6.08", tier: "Round 4", strengths: "Receiving ability, size, red zone", comparison: "Ceiling: Foster Moreau, Floor: Donald Parham" },
    { rank: 83, name: "Jake Slaughter", position: "IOL", school: "Florida", height: "6'4\"", weight: 294, grade: "6.08", tier: "Round 4", strengths: "Technique, power, versatility", comparison: "Ceiling: Damien Lewis, Floor: Cody Whitehair" },
    { rank: 84, name: "Emmett Johnson", position: "RB", school: "Nebraska", height: "6'0\"", weight: 210, grade: "6.08", tier: "Round 4", strengths: "Vision, patience, contact balance", comparison: "Ceiling: Josh Jacobs, Floor: Alexander Mattison" },
    { rank: 85, name: "Davison Igbinosun", position: "CB", school: "Ohio State", height: "6'2\"", weight: 193, grade: "6.08", tier: "Round 4", strengths: "Size, press coverage, ball skills", comparison: "Ceiling: Richard Sherman, Floor: Ahkello Witherspoon" },
    { rank: 86, name: "Anthony Lucas", position: "EDGE", school: "USC", height: "6'5\"", weight: 285, grade: "6.05", tier: "Round 4", strengths: "Size, power, developmental", comparison: "Ceiling: Arik Armstead, Floor: Rasheem Green" },
    { rank: 87, name: "Genesis Smith", position: "S", school: "Arizona", height: "6'2\"", weight: 204, grade: "6.05", tier: "Round 4", strengths: "Range, tackling, instincts", comparison: "Ceiling: Kevin Byard, Floor: Marcus Gilchrist" },
    { rank: 88, name: "Chandler Rivers", position: "CB", school: "Duke", height: "5'10\"", weight: 180, grade: "6.05", tier: "Round 5", strengths: "Technique, coverage, ball skills", comparison: "Ceiling: Kenny Moore II, Floor: Tavon Young" },
    { rank: 89, name: "Deion Burks", position: "WR", school: "Oklahoma", height: "5'9\"", weight: 189, grade: "6.05", tier: "Round 5", strengths: "Speed, quickness, return ability", comparison: "Ceiling: Mecole Hardman, Floor: Ray-Ray McCloud" },
    { rank: 90, name: "Austin Barber", position: "OT", school: "Florida", height: "6'6\"", weight: 322, grade: "6.02", tier: "Round 5", strengths: "Size, power, developmental", comparison: "Ceiling: Jawaan Taylor, Floor: Bobby Hart" },
    { rank: 91, name: "Carson Beck", position: "QB", school: "Miami", height: "6'4\"", weight: 220, grade: "6.02", tier: "Round 5", strengths: "Size, arm strength, pocket presence", comparison: "Ceiling: Ben Roethlisberger, Floor: Christian Hackenberg" },
    { rank: 92, name: "Will Lee III", position: "CB", school: "Texas A&M", height: "6'3\"", weight: 190, grade: "6.02", tier: "Round 5", strengths: "Size, length, press coverage", comparison: "Ceiling: Richard Sherman, Floor: Ahkello Witherspoon" },
    { rank: 93, name: "Treydan Stukes", position: "CB", school: "Arizona", height: "6'2\"", weight: 200, grade: "6.00", tier: "Round 5", strengths: "Size, physicality, ball skills", comparison: "Ceiling: Patrick Surtain II, Floor: Fabian Moreau" },
    { rank: 94, name: "Devin Moore", position: "CB", school: "Florida", height: "6'2\"", weight: 198, grade: "6.00", tier: "Round 5", strengths: "Size, length, developmental", comparison: "Ceiling: Jaycee Horn, Floor: Kei'Trel Clark" },
    { rank: 95, name: "Taurean York", position: "LB", school: "Texas A&M", height: "6'0\"", weight: 235, grade: "6.00", tier: "Round 5", strengths: "Tackling, instincts, run defense", comparison: "Ceiling: Eric Kendricks, Floor: Sio Moore" },
    { rank: 96, name: "Nicholas Singleton", position: "RB", school: "Penn State", height: "6'0\"", weight: 224, grade: "6.00", tier: "Round 5", strengths: "Speed, power, home run ability", comparison: "Ceiling: Saquon Barkley, Floor: Sony Michel" },
    { rank: 97, name: "Jack Endries", position: "TE", school: "Texas", height: "6'4\"", weight: 236, grade: "5.98", tier: "Round 5", strengths: "Receiving, route running, hands", comparison: "Ceiling: Cole Kmet, Floor: Durham Smythe" },
    { rank: 98, name: "Skyler Bell", position: "WR", school: "UConn", height: "6'0\"", weight: 185, grade: "5.98", tier: "Round 5", strengths: "Speed, production, return ability", comparison: "Ceiling: Tyler Lockett, Floor: Darius Slayton" },
    { rank: 99, name: "Dontay Corleone", position: "DL", school: "Cincinnati", height: "6'2\"", weight: 318, grade: "5.98", tier: "Round 5", strengths: "Size, power, run defense", comparison: "Ceiling: D.J. Reader, Floor: Tyler Shelvin" },
    { rank: 100, name: "Harold Perkins Jr.", position: "LB", school: "LSU", height: "6'1\"", weight: 225, grade: "5.95", tier: "Round 5", strengths: "Speed, blitz ability, coverage", comparison: "Ceiling: Micah Parsons, Floor: Jarrad Davis" },

    { rank: 101, name: "Drew Shelton", position: "OT", school: "Penn State", height: "6'5\"", weight: 305, grade: "5.95", tier: "Round 5", strengths: "Technique, power, developmental", comparison: "Ceiling: Mitch Morse, Floor: Chukwuma Okorafor" },
    { rank: 102, name: "Kaytron Allen", position: "RB", school: "Penn State", height: "5'11\"", weight: 219, grade: "5.95", tier: "Round 5", strengths: "Power, vision, durability", comparison: "Ceiling: Kareem Hunt, Floor: Cam Akers" },
    { rank: 103, name: "Zakee Wheatley", position: "S", school: "Penn State", height: "6'2\"", weight: 202, grade: "5.95", tier: "Round 5", strengths: "Speed, range, ball skills", comparison: "Ceiling: Kevin Byard, Floor: Marcus Gilchrist" },
    { rank: 104, name: "Malachi Lawrence", position: "EDGE", school: "UCF", height: "6'4\"", weight: 260, grade: "5.92", tier: "Round 5", strengths: "Speed rush, bend, motor", comparison: "Ceiling: Yannick Ngakoue, Floor: Josh Uche" },
    { rank: 105, name: "Chris McClellan", position: "DL", school: "Missouri", height: "6'4\"", weight: 323, grade: "5.92", tier: "Round 5", strengths: "Power, run defense, size", comparison: "Ceiling: D.J. Reader, Floor: Tyler Shelvin" },
    { rank: 106, name: "Brian Parker II", position: "OT", school: "Duke", height: "6'5\"", weight: 305, grade: "5.92", tier: "Round 5", strengths: "Technique, developmental, power", comparison: "Ceiling: Mitch Morse, Floor: Chukwuma Okorafor" },
    { rank: 107, name: "Daylen Everette", position: "CB", school: "Georgia", height: "6'1\"", weight: 190, grade: "5.92", tier: "Round 5", strengths: "Technique, experience, physicality", comparison: "Ceiling: Jaire Alexander, Floor: Sean Murphy-Bunting" },
    { rank: 108, name: "Ted Hurst", position: "WR", school: "Georgia State", height: "6'3\"", weight: 195, grade: "5.90", tier: "Round 5", strengths: "Size, production, contested catches", comparison: "Ceiling: Courtland Sutton, Floor: Breshad Perriman" },
    { rank: 109, name: "Lander Barton", position: "LB", school: "Utah", height: "6'5\"", weight: 240, grade: "5.90", tier: "Round 6", strengths: "Size, length, developmental", comparison: "Ceiling: Blake Martinez, Floor: Ben Boulware" },
    { rank: 110, name: "Garrett Nussmeier", position: "QB", school: "LSU", height: "6'1\"", weight: 205, grade: "5.90", tier: "Round 6", strengths: "Quick release, arm talent, playmaking", comparison: "Ceiling: Derek Carr, Floor: Brian Hoyer" },
    { rank: 111, name: "Jaishawn Barham", position: "LB", school: "Michigan", height: "6'3\"", weight: 243, grade: "5.88", tier: "Round 6", strengths: "Athleticism, versatility, upside", comparison: "Ceiling: Micah Parsons, Floor: Jarrad Davis" },
    { rank: 112, name: "Jude Bowry", position: "OT", school: "Boston College", height: "6'5\"", weight: 308, grade: "5.88", tier: "Round 6", strengths: "Size, technique, developmental", comparison: "Ceiling: Mitch Morse, Floor: Chukwuma Okorafor" },
    { rank: 113, name: "Gracen Halton", position: "DL", school: "Oklahoma", height: "6'2\"", weight: 292, grade: "5.88", tier: "Round 6", strengths: "Power, technique, motor", comparison: "Ceiling: D.J. Reader, Floor: Tyler Shelvin" },
    { rank: 114, name: "Caden Curry", position: "EDGE", school: "Ohio State", height: "6'3\"", weight: 260, grade: "5.88", tier: "Round 6", strengths: "Speed, bend, production", comparison: "Ceiling: Brian Burns, Floor: Josh Uche" },
    { rank: 115, name: "Jalon Kilgore", position: "S", school: "South Carolina", height: "6'1\"", weight: 211, grade: "5.85", tier: "Round 6", strengths: "Range, ball skills, tackling", comparison: "Ceiling: Xavier McKinney, Floor: Terrell Edmunds" },
    { rank: 116, name: "Dametrious Crownover", position: "OT", school: "Texas A&M", height: "6'7\"", weight: 336, grade: "5.85", tier: "Round 6", strengths: "Size, power, developmental", comparison: "Ceiling: Mekhi Becton, Floor: Germain Ifedi" },
    { rank: 117, name: "Mikail Kamara", position: "EDGE", school: "Indiana", height: "6'1\"", weight: 265, grade: "5.85", tier: "Round 6", strengths: "Speed rush, motor, production", comparison: "Ceiling: Yannick Ngakoue, Floor: Josh Uche" },
    { rank: 118, name: "Bud Clark", position: "S", school: "TCU", height: "6'2\"", weight: 190, grade: "5.82", tier: "Round 6", strengths: "Ball skills, instincts, range", comparison: "Ceiling: Kevin Byard, Floor: Marcus Gilchrist" },
    { rank: 119, name: "CJ Daniels", position: "WR", school: "Miami", height: "6'2\"", weight: 205, grade: "5.82", tier: "Round 6", strengths: "Size, contested catches, red zone", comparison: "Ceiling: Michael Thomas, Floor: Equanimeous St. Brown" },
    { rank: 120, name: "Sam Hecht", position: "IOL", school: "Kansas State", height: "6'4\"", weight: 300, grade: "5.82", tier: "Round 6", strengths: "Technique, power, developmental", comparison: "Ceiling: Ryan Kelly, Floor: Matt Skura" },
    { rank: 121, name: "Justin Joly", position: "TE", school: "NC State", height: "6'3\"", weight: 263, grade: "5.80", tier: "Round 6", strengths: "Size, receiving, red zone", comparison: "Ceiling: Foster Moreau, Floor: Donald Parham" },
    { rank: 122, name: "Keylan Rutledge", position: "IOL", school: "Georgia Tech", height: "6'4\"", weight: 330, grade: "5.80", tier: "Round 6", strengths: "Size, power, run blocking", comparison: "Ceiling: Shaq Mason, Floor: Josh Jones" },
    { rank: 123, name: "Michael Taaffe", position: "S", school: "Texas", height: "6'0\"", weight: 189, grade: "5.80", tier: "Round 6", strengths: "Speed, tackling, special teams", comparison: "Ceiling: Xavier McKinney, Floor: Terrell Edmunds" },
    { rank: 124, name: "Ar'maj Reed-Adams", position: "IOL", school: "Texas A&M", height: "6'5\"", weight: 340, grade: "5.78", tier: "Round 6", strengths: "Size, power, developmental", comparison: "Ceiling: Quenton Nelson, Floor: Isaiah Wilson" },
    { rank: 125, name: "Kyle Louis", position: "LB", school: "Pittsburgh", height: "6'1\"", weight: 220, grade: "5.78", tier: "Round 6", strengths: "Speed, tackling, instincts", comparison: "Ceiling: Alex Anzalone, Floor: Krys Barnes" },
    { rank: 126, name: "Zane Durant", position: "DL", school: "Penn State", height: "6'1\"", weight: 292, grade: "5.78", tier: "Round 6", strengths: "Quickness, power, motor", comparison: "Ceiling: Grady Jarrett, Floor: Poona Ford" },
    { rank: 127, name: "Tyreak Sapp", position: "EDGE", school: "Florida", height: "6'3\"", weight: 274, grade: "5.75", tier: "Round 6", strengths: "Power, run defense, developmental", comparison: "Ceiling: Montez Sweat, Floor: Romeo Okwara" },
    { rank: 128, name: "Eli Raridon", position: "TE", school: "Notre Dame", height: "6'7\"", weight: 252, grade: "5.75", tier: "Round 6", strengths: "Size, receiving, developmental", comparison: "Ceiling: Cole Kmet, Floor: Durham Smythe" },
    { rank: 129, name: "Demond Claiborne", position: "RB", school: "Wake Forest", height: "5'10\"", weight: 195, grade: "5.75", tier: "Round 6", strengths: "Speed, quickness, return ability", comparison: "Ceiling: Devin Singletary, Floor: Explosive change-of-pace" },
    { rank: 130, name: "Tim Keenan III", position: "DL", school: "Alabama", height: "6'2\"", weight: 325, grade: "5.75", tier: "Round 6", strengths: "Size, power, run defense", comparison: "Ceiling: Vita Vea, Floor: Danny Shelton" },
    { rank: 131, name: "Rayshaun Benny", position: "DL", school: "Michigan", height: "6'4\"", weight: 305, grade: "5.75", tier: "Round 6", strengths: "Power, run defense, size", comparison: "Ceiling: D.J. Reader, Floor: Tyler Shelvin" },
    { rank: 132, name: "Dallen Bentley", position: "TE", school: "Utah", height: "6'4\"", weight: 259, grade: "5.75", tier: "Round 6", strengths: "Size, receiving, blocking", comparison: "Ceiling: Cole Kmet, Floor: Durham Smythe" },
    { rank: 133, name: "Eric Rivers", position: "WR", school: "Georgia Tech", height: "5'11\"", weight: 180, grade: "5.75", tier: "Round 6", strengths: "Speed, quickness, YAC", comparison: "Ceiling: Tyler Lockett, Floor: Darius Slayton" },
    { rank: 134, name: "Josh Cameron", position: "WR", school: "Baylor", height: "6'1\"", weight: 224, grade: "5.72", tier: "Round 6", strengths: "Size, contested catches, red zone", comparison: "Ceiling: Courtland Sutton, Floor: Miles Boykin" },
    { rank: 135, name: "Zxavian Harris", position: "DL", school: "Ole Miss", height: "6'7\"", weight: 320, grade: "5.72", tier: "Round 6", strengths: "Size, power, developmental", comparison: "Ceiling: Vita Vea, Floor: Danny Shelton" },
    { rank: 136, name: "Jaeden Roberts", position: "IOL", school: "Alabama", height: "6'5\"", weight: 310, grade: "5.72", tier: "Round 6", strengths: "Power, run blocking, developmental", comparison: "Ceiling: Shaq Mason, Floor: Josh Jones" },
    { rank: 137, name: "Kage Casey", position: "OT", school: "Boise State", height: "6'5\"", weight: 316, grade: "5.70", tier: "Round 6", strengths: "Size, technique, developmental", comparison: "Ceiling: Mitch Morse, Floor: Chukwuma Okorafor" },
    { rank: 138, name: "Aaron Anderson", position: "WR", school: "LSU", height: "5'8\"", weight: 188, grade: "5.70", tier: "Round 6", strengths: "Speed, quickness, return ability", comparison: "Ceiling: Mecole Hardman, Floor: Ray-Ray McCloud" },
    { rank: 139, name: "Aiden Fisher", position: "LB", school: "Indiana", height: "6'1\"", weight: 231, grade: "5.70", tier: "Round 6", strengths: "Tackling, instincts, production", comparison: "Ceiling: Blake Martinez, Floor: Ben Boulware" },
    { rank: 140, name: "Eric McAlister", position: "WR", school: "TCU", height: "6'3\"", weight: 205, grade: "5.70", tier: "Round 6", strengths: "Size, contested catches, deep threat", comparison: "Ceiling: Courtland Sutton, Floor: Miles Boykin" },
    { rank: 141, name: "John Michael Gyllenborg", position: "TE", school: "Wyoming", height: "6'5\"", weight: 251, grade: "5.68", tier: "Round 6", strengths: "Size, blocking, developmental", comparison: "Ceiling: Tommy Tremble, Floor: Practice squad" },
    { rank: 142, name: "TJ Hall", position: "CB", school: "Iowa", height: "6'0\"", weight: 190, grade: "5.68", tier: "Round 6", strengths: "Technique, coverage, ball skills", comparison: "Ceiling: Kenny Moore II, Floor: Tavon Young" },
    { rank: 143, name: "J'Mari Taylor", position: "RB", school: "Virginia", height: "5'9\"", weight: 204, grade: "5.68", tier: "Round 6", strengths: "Speed, vision, production", comparison: "Ceiling: Devin Singletary, Floor: Change-of-pace" },
    { rank: 144, name: "DeMonte Capehart", position: "DL", school: "Clemson", height: "6'5\"", weight: 315, grade: "5.68", tier: "Round 6", strengths: "Size, power, developmental", comparison: "Ceiling: Vita Vea, Floor: Danny Shelton" },
    { rank: 145, name: "Sawyer Robertson", position: "QB", school: "Baylor", height: "6'4\"", weight: 220, grade: "5.68", tier: "Round 6", strengths: "Size, arm strength, leadership", comparison: "Ceiling: Carson Palmer, Floor: Jacob Eason" },
    { rank: 146, name: "Max Llewellyn", position: "EDGE", school: "Iowa", height: "6'5\"", weight: 263, grade: "5.68", tier: "Round 6", strengths: "Power, technique, motor", comparison: "Ceiling: Montez Sweat, Floor: Romeo Okwara" },
    { rank: 147, name: "Thaddeus Dixon", position: "CB", school: "North Carolina", height: "6'1\"", weight: 195, grade: "5.68", tier: "Round 6", strengths: "Size, length, developmental", comparison: "Ceiling: Patrick Surtain II, Floor: Fabian Moreau" },
    { rank: 148, name: "Marlin Klein", position: "TE", school: "Michigan", height: "6'6\"", weight: 250, grade: "5.65", tier: "Round 6", strengths: "Size, receiving, developmental", comparison: "Ceiling: Cole Kmet, Floor: Durham Smythe" },
    { rank: 149, name: "Dae'Quan Wright", position: "TE", school: "Ole Miss", height: "6'4\"", weight: 255, grade: "5.65", tier: "Round 6", strengths: "Size, receiving, red zone", comparison: "Ceiling: Foster Moreau, Floor: Donald Parham" },
    { rank: 150, name: "Bishop Fitzgerald", position: "S", school: "USC", height: "5'11\"", weight: 205, grade: "5.65", tier: "Round 6", strengths: "Ball skills, instincts, range", comparison: "Ceiling: Kevin Byard, Floor: Marcus Gilchrist" },
    { rank: 151, name: "Trey Moore", position: "EDGE", school: "Texas", height: "6'3\"", weight: 249, grade: "5.65", tier: "Round 6", strengths: "Speed rush, bend, motor", comparison: "Ceiling: Brian Burns, Floor: Josh Uche" },
    { rank: 152, name: "Trey Zuhn III", position: "OT", school: "Texas A&M", height: "6'7\"", weight: 315, grade: "5.65", tier: "Round 6", strengths: "Size, power, developmental", comparison: "Ceiling: Mekhi Becton, Floor: Germain Ifedi" },
    { rank: 153, name: "Keyron Crawford", position: "EDGE", school: "Auburn", height: "6'4\"", weight: 255, grade: "5.65", tier: "Round 6", strengths: "Speed, bend, developmental", comparison: "Ceiling: Yannick Ngakoue, Floor: Josh Uche" },
    { rank: 154, name: "Cole Payton", position: "QB", school: "North Dakota State", height: "6'3\"", weight: 225, grade: "5.65", tier: "Round 6", strengths: "Dual-threat, arm strength, FCS pedigree", comparison: "Ceiling: Trey Lance, Floor: Easton Stick" },
    { rank: 155, name: "Jaxson Dart", position: "QB", school: "Ole Miss", height: "6'2\"", weight: 220, grade: "5.65", tier: "Round 6", strengths: "Mobility, arm talent, competitive", comparison: "Ceiling: Derek Carr, Floor: Josh Dobbs" },
    { rank: 156, name: "Will Rogers", position: "QB", school: "Washington", height: "6'2\"", weight: 210, grade: "5.62", tier: "Round 7", strengths: "Accuracy, quick release, anticipation", comparison: "Ceiling: Drew Brees, Floor: Case Keenum" },
    { rank: 157, name: "Maalik Murphy", position: "QB", school: "Duke", height: "6'5\"", weight: 230, grade: "5.62", tier: "Round 7", strengths: "Arm strength, size, upside", comparison: "Ceiling: Josh Allen, Floor: E.J. Manuel" },
    { rank: 158, name: "Brady Cook", position: "QB", school: "Missouri", height: "6'2\"", weight: 215, grade: "5.60", tier: "Round 7", strengths: "Athleticism, leadership, toughness", comparison: "Ceiling: Alex Smith, Floor: Jake Fromm" },
    { rank: 159, name: "Jordan McCloud", position: "QB", school: "Texas State", height: "6'3\"", weight: 220, grade: "5.58", tier: "Round 7", strengths: "Accuracy, mobility, production", comparison: "Ceiling: Ryan Tannehill, Floor: Nick Mullens" },
    { rank: 160, name: "Kyle McCord", position: "QB", school: "Syracuse", height: "6'3\"", weight: 215, grade: "5.58", tier: "Round 7", strengths: "Pocket presence, arm strength, anticipation", comparison: "Ceiling: Kirk Cousins, Floor: Sean Clifford" },
    { rank: 161, name: "Conner Weigman", position: "QB", school: "Texas A&M", height: "6'3\"", weight: 218, grade: "5.55", tier: "Round 7", strengths: "Arm talent, poise, pocket awareness", comparison: "Ceiling: Matthew Stafford, Floor: Jarrett Stidham" },
    { rank: 162, name: "Brock Vandagriff", position: "QB", school: "Georgia", height: "6'3\"", weight: 215, grade: "5.55", tier: "Round 7", strengths: "Arm strength, athleticism, upside", comparison: "Ceiling: Jay Cutler, Floor: Logan Thomas" },
    { rank: 163, name: "Miller Moss", position: "QB", school: "Louisville", height: "6'2\"", weight: 210, grade: "5.52", tier: "Round 7", strengths: "Accuracy, anticipation, processing", comparison: "Ceiling: Jared Goff, Floor: Davis Webb" },
    { rank: 164, name: "Tyler Van Dyke", position: "QB", school: "Wisconsin", height: "6'4\"", weight: 225, grade: "5.50", tier: "Round 7", strengths: "Size, arm strength, pro-style", comparison: "Ceiling: Ben Roethlisberger, Floor: Nathan Peterman" },
    { rank: 165, name: "Hayden Wolff", position: "QB", school: "Western Kentucky", height: "6'5\"", weight: 230, grade: "5.50", tier: "Round 7", strengths: "Size, pocket presence, leadership", comparison: "Ceiling: Joe Flacco, Floor: Mike Glennon" },
    { rank: 166, name: "Grayson McCall", position: "QB", school: "NC State", height: "6'3\"", weight: 210, grade: "5.48", tier: "Round 7", strengths: "Accuracy, efficiency, decision-making", comparison: "Ceiling: Mac Jones, Floor: Chase Daniel" },
    { rank: 167, name: "Chevan Cordeiro", position: "QB", school: "San Jose State", height: "6'1\"", weight: 205, grade: "5.48", tier: "Round 7", strengths: "Mobility, playmaking, leadership", comparison: "Ceiling: Russell Wilson, Floor: Chris Streveler" },
    { rank: 168, name: "Avery Johnson", position: "QB", school: "Kansas State", height: "6'2\"", weight: 200, grade: "5.45", tier: "Round 7", strengths: "Athleticism, arm talent, dual-threat", comparison: "Ceiling: Jalen Hurts, Floor: Taysom Hill" },
    { rank: 169, name: "Khalib Johnson", position: "QB", school: "Eastern Michigan", height: "6'3\"", weight: 220, grade: "5.45", tier: "Round 7", strengths: "Arm strength, size, pro potential", comparison: "Ceiling: Tyrod Taylor, Floor: Geno Smith" },
    { rank: 170, name: "John Mateer", position: "QB", school: "Washington State", height: "6'1\"", weight: 215, grade: "5.42", tier: "Round 7", strengths: "Athleticism, toughness, running ability", comparison: "Ceiling: Tim Tebow, Floor: Tommy Stevens" },
    { rank: 171, name: "Jalen Milroe", position: "QB", school: "Alabama", height: "6'2\"", weight: 220, grade: "5.40", tier: "Round 7", strengths: "Elite athleticism, arm strength, upside", comparison: "Ceiling: Justin Fields, Floor: Malik Willis" },
    { rank: 172, name: "LaNorris Sellers", position: "QB", school: "South Carolina", height: "6'3\"", weight: 225, grade: "5.40", tier: "Round 7", strengths: "Dual-threat, arm strength, leadership", comparison: "Ceiling: Cam Newton, Floor: Logan Thomas" },
    { rank: 173, name: "Dante Reno", position: "QB", school: "Boston College", height: "6'3\"", weight: 215, grade: "5.38", tier: "Round 7", strengths: "Accuracy, pocket presence, size", comparison: "Ceiling: Andy Dalton, Floor: Clayton Thorson" },
    { rank: 174, name: "Tavien St. Clair", position: "QB", school: "Ohio State", height: "6'4\"", weight: 230, grade: "5.38", tier: "Round 7", strengths: "Size, arm strength, pro-style", comparison: "Ceiling: Byron Leftwich, Floor: Cardale Jones" },
    { rank: 175, name: "Jack Larsen", position: "QB", school: "NC State", height: "6'2\"", weight: 210, grade: "5.35", tier: "Round 7", strengths: "Accuracy, leadership, consistency", comparison: "Ceiling: Mike Glennon, Floor: Jacoby Brissett" },
    { rank: 176, name: "Cade Klubnik", position: "QB", school: "Clemson", height: "6'2\"", weight: 205, grade: "5.35", tier: "Round 7", strengths: "Athleticism, arm talent, upside", comparison: "Ceiling: Sam Darnold, Floor: Christian Ponder" },
    { rank: 177, name: "Devin Brown", position: "QB", school: "Oklahoma", height: "6'3\"", weight: 218, grade: "5.35", tier: "Round 7", strengths: "Arm strength, size, potential", comparison: "Ceiling: Davis Mills, Floor: Practice squad" },
    { rank: 178, name: "Garrett Greene", position: "QB", school: "West Virginia", height: "6'0\"", weight: 205, grade: "5.32", tier: "Round 7", strengths: "Athleticism, playmaking, dual-threat", comparison: "Ceiling: Trace McSorley, Floor: Practice squad" },
    { rank: 179, name: "Preston Stone", position: "QB", school: "Tulsa", height: "6'2\"", weight: 210, grade: "5.30", tier: "Round 7", strengths: "Pocket presence, accuracy, football IQ", comparison: "Ceiling: Chase Daniel, Floor: Practice squad" },
    { rank: 180, name: "Tyler Shough", position: "QB", school: "Louisville", height: "6'5\"", weight: 230, grade: "5.30", tier: "Round 7", strengths: "Size, experience, pro-style", comparison: "Ceiling: Trevor Siemian, Floor: Practice squad" },
    { rank: 181, name: "Kaleb Johnson", position: "RB", school: "Iowa", height: "6'0\"", weight: 220, grade: "5.80", tier: "Round 6", strengths: "Power, vision, physicality", comparison: "Ceiling: Nick Chubb, Floor: Benny Snell" },
    { rank: 182, name: "Kalel Mullings", position: "RB", school: "Michigan", height: "6'2\"", weight: 230, grade: "5.78", tier: "Round 6", strengths: "Size, power, downhill running", comparison: "Ceiling: Derrick Henry, Floor: Latavius Murray" },
    { rank: 183, name: "Trevor Etienne", position: "RB", school: "Georgia", height: "5'9\"", weight: 205, grade: "5.75", tier: "Round 6", strengths: "Explosiveness, speed, receiving", comparison: "Ceiling: Dalvin Cook, Floor: Tarik Cohen" },
    { rank: 184, name: "Donovan Edwards", position: "RB", school: "Michigan", height: "5'11\"", weight: 200, grade: "5.72", tier: "Round 6", strengths: "Speed, receiving, versatility", comparison: "Ceiling: Alvin Kamara, Floor: Theo Riddick" },
    { rank: 185, name: "Tahj Brooks", position: "RB", school: "Texas Tech", height: "5'10\"", weight: 225, grade: "5.70", tier: "Round 6", strengths: "Size, power, durability", comparison: "Ceiling: Chris Carson, Floor: Royce Freeman" },
    { rank: 186, name: "Ulysses Bentley", position: "RB", school: "Ole Miss", height: "5'10\"", weight: 195, grade: "5.68", tier: "Round 6", strengths: "Quickness, receiving, elusiveness", comparison: "Ceiling: Duke Johnson, Floor: Dontrell Hilliard" },
    { rank: 187, name: "Kye Robichaux", position: "RB", school: "Baylor", height: "6'0\"", weight: 215, grade: "5.68", tier: "Round 6", strengths: "Vision, patience, power", comparison: "Ceiling: Damien Harris, Floor: Brian Hill" },
    { rank: 188, name: "Damien Martinez", position: "RB", school: "Texas A&M", height: "6'0\"", weight: 225, grade: "5.65", tier: "Round 6", strengths: "Size, physicality, youth", comparison: "Ceiling: Rhamondre Stevenson, Floor: Larry Rountree" },
    { rank: 189, name: "Cam Skattebo", position: "RB", school: "Arizona State", height: "5'11\"", weight: 220, grade: "5.65", tier: "Round 6", strengths: "Power, versatility, toughness", comparison: "Ceiling: Peyton Hillis, Floor: Rex Burkhead" },
    { rank: 190, name: "Branson Robinson", position: "RB", school: "Georgia", height: "5'10\"", weight: 220, grade: "5.62", tier: "Round 6", strengths: "Power, explosiveness, limited usage", comparison: "Ceiling: Sony Michel, Floor: D'Onta Foreman" },
    { rank: 191, name: "Phil Mafah", position: "RB", school: "Clemson", height: "6'1\"", weight: 230, grade: "5.62", tier: "Round 6", strengths: "Size, power, durability", comparison: "Ceiling: Jordan Howard, Floor: Practice squad" },
    { rank: 192, name: "RJ Harvey", position: "RB", school: "UCF", height: "5'11\"", weight: 205, grade: "5.60", tier: "Round 7", strengths: "Speed, explosiveness, big play ability", comparison: "Ceiling: Austin Ekeler, Floor: Justin Jackson" },
    { rank: 193, name: "Le'Veon Moss", position: "RB", school: "Texas A&M", height: "5'11\"", weight: 210, grade: "5.58", tier: "Round 7", strengths: "Three-down ability, versatile, pass pro", comparison: "Ceiling: Damien Pierce, Floor: Reliable backup" },
    { rank: 194, name: "Jarquez Hunter", position: "RB", school: "Auburn", height: "5'10\"", weight: 200, grade: "5.55", tier: "Round 7", strengths: "Quickness, SEC experience, return ability", comparison: "Ceiling: Giovanni Bernard, Floor: Practice squad" },
    { rank: 195, name: "Kaelon Black", position: "RB", school: "Army", height: "6'0\"", weight: 215, grade: "5.52", tier: "Round 7", strengths: "Scheme versatility, intelligence, blocking", comparison: "Ceiling: Zac Brooks, Floor: Fullback convert" },
    { rank: 196, name: "Jalen White", position: "RB", school: "Georgia Southern", height: "5'11\"", weight: 205, grade: "5.50", tier: "Round 7", strengths: "Speed, receiving, Sun Belt production", comparison: "Ceiling: Jerick McKinnon, Floor: Practice squad" },
    { rank: 197, name: "Tez Johnson", position: "WR", school: "Oregon", height: "5'10\"", weight: 175, grade: "5.88", tier: "Round 6", strengths: "Speed, quickness, route running", comparison: "Ceiling: Tyler Lockett, Floor: Darius Slayton" },
    { rank: 198, name: "Xavier Restrepo", position: "WR", school: "Miami", height: "5'9\"", weight: 190, grade: "5.85", tier: "Round 6", strengths: "Quickness, slot ability, return skills", comparison: "Ceiling: Julian Edelman, Floor: Braxton Berrios" },
    { rank: 199, name: "Elic Ayomanor", position: "WR", school: "Stanford", height: "6'2\"", weight: 210, grade: "5.85", tier: "Round 6", strengths: "Size, contested catches, physicality", comparison: "Ceiling: Michael Pittman, Floor: JJ Arcega-Whiteside" },
    { rank: 200, name: "Luther Burden", position: "WR", school: "Georgia", height: "5'11\"", weight: 195, grade: "5.82", tier: "Round 6", strengths: "YAC ability, toughness, versatility", comparison: "Ceiling: Deebo Samuel, Floor: Laviska Shenault" },
    { rank: 201, name: "Kyle Williams", position: "WR", school: "Washington State", height: "6'0\"", weight: 185, grade: "5.80", tier: "Round 6", strengths: "Speed, route running, deep threat", comparison: "Ceiling: Terry McLaurin, Floor: Darius Slayton" },
    { rank: 202, name: "Barion Brown", position: "WR", school: "Kentucky", height: "6'1\"", weight: 195, grade: "5.78", tier: "Round 6", strengths: "Speed, size, contested catch ability", comparison: "Ceiling: Mike Evans, Floor: Josh Reynolds" },
    { rank: 203, name: "Jack Bech", position: "WR", school: "TCU", height: "6'2\"", weight: 215, grade: "5.78", tier: "Round 6", strengths: "Size, hands, red zone threat", comparison: "Ceiling: Michael Thomas, Floor: Equanimeous St. Brown" },
    { rank: 204, name: "Jalen Royals", position: "WR", school: "Utah State", height: "6'0\"", weight: 200, grade: "5.75", tier: "Round 6", strengths: "Route running, contested catches, production", comparison: "Ceiling: Chris Godwin, Floor: DaeSean Hamilton" },
    { rank: 205, name: "Tre Harris", position: "WR", school: "Ole Miss", height: "6'2\"", weight: 205, grade: "5.75", tier: "Round 6", strengths: "Size, physicality, red zone threat", comparison: "Ceiling: Courtland Sutton, Floor: Breshad Perriman" },
    { rank: 206, name: "Pat Bryant", position: "WR", school: "Florida State", height: "6'3\"", weight: 210, grade: "5.72", tier: "Round 6", strengths: "Size, contested catches, development", comparison: "Ceiling: Kenny Golladay, Floor: Hakeem Butler" },
    { rank: 207, name: "Tahj Washington", position: "WR", school: "USC", height: "5'10\"", weight: 180, grade: "5.72", tier: "Round 7", strengths: "Speed, quickness, slot ability", comparison: "Ceiling: KJ Hamler, Floor: Steven Sims" },
    { rank: 208, name: "Will Sheppard", position: "WR", school: "Colorado", height: "6'3\"", weight: 200, grade: "5.70", tier: "Round 7", strengths: "Size, contested catches, physicality", comparison: "Ceiling: Courtland Sutton, Floor: Miles Boykin" },
    { rank: 209, name: "Isaac TeSlaa", position: "WR", school: "Arkansas", height: "6'4\"", weight: 215, grade: "5.68", tier: "Round 7", strengths: "Size, red zone ability, developmental", comparison: "Ceiling: Auden Tate, Floor: Practice squad" },
    { rank: 210, name: "Montrell Johnson", position: "WR", school: "Florida", height: "6'0\"", weight: 195, grade: "5.68", tier: "Round 7", strengths: "Athleticism, contested catches, upside", comparison: "Ceiling: Allen Lazard, Floor: Justin Watson" },
    { rank: 211, name: "Dante Wright", position: "WR", school: "Colorado", height: "5'10\"", weight: 185, grade: "5.65", tier: "Round 7", strengths: "Speed, quickness, versatility", comparison: "Ceiling: Curtis Samuel, Floor: DeAndre Carter" },
    { rank: 212, name: "Lonnie Galloway", position: "WR", school: "West Virginia", height: "5'11\"", weight: 190, grade: "5.65", tier: "Round 7", strengths: "Route running, quickness, hands", comparison: "Ceiling: Sterling Shepard, Floor: Trent Taylor" },
    { rank: 213, name: "Evan Prater", position: "WR", school: "Cincinnati", height: "6'0\"", weight: 195, grade: "5.62", tier: "Round 7", strengths: "Athleticism, YAC ability, development", comparison: "Ceiling: Russell Gage, Floor: Practice squad" },
    { rank: 214, name: "Marcus Rosemy-Jacksaint", position: "WR", school: "Georgia", height: "6'1\"", weight: 205, grade: "5.62", tier: "Round 7", strengths: "Size, contested catches, blocking", comparison: "Ceiling: Miles Boykin, Floor: Practice squad" },
    { rank: 215, name: "Kris Mitchell", position: "WR", school: "Miami", height: "6'2\"", weight: 200, grade: "5.60", tier: "Round 7", strengths: "Size, contested catches, red zone", comparison: "Ceiling: Chris Conley, Floor: Practice squad" },
    { rank: 216, name: "Connor Gibson", position: "WR", school: "Texas", height: "6'3\"", weight: 215, grade: "5.58", tier: "Round 7", strengths: "Size, physicality, developmental", comparison: "Ceiling: Equanimeous St. Brown, Floor: Practice squad" },
    { rank: 217, name: "Jordan Moore", position: "WR", school: "Texas A&M", height: "6'0\"", weight: 195, grade: "5.58", tier: "Round 7", strengths: "Route running, hands, possession", comparison: "Ceiling: Alex Erickson, Floor: Practice squad" },
    { rank: 218, name: "TreShawn Holden", position: "WR", school: "Oregon", height: "6'1\"", weight: 200, grade: "5.55", tier: "Round 7", strengths: "Size, contested catches, upside", comparison: "Ceiling: Tyrell Williams, Floor: Practice squad" },
    { rank: 219, name: "Jabari Camper", position: "WR", school: "Louisville", height: "6'4\"", weight: 210, grade: "5.55", tier: "Round 7", strengths: "Size, developmental, red zone", comparison: "Ceiling: Travis Fulgham, Floor: Practice squad" },
    { rank: 220, name: "Marcus Alexander", position: "WR", school: "NC State", height: "5'11\"", weight: 190, grade: "5.52", tier: "Round 7", strengths: "Quickness, return ability, special teams", comparison: "Ceiling: Alex Erickson, Floor: Practice squad" },
    { rank: 221, name: "Christian Lewis", position: "WR", school: "Alabama", height: "6'2\"", weight: 205, grade: "5.52", tier: "Round 7", strengths: "Size, blocking, developmental", comparison: "Ceiling: Kevin White, Floor: Practice squad" },
    { rank: 222, name: "Elijah Banks", position: "WR", school: "Ole Miss", height: "6'0\"", weight: 195, grade: "5.50", tier: "Round 7", strengths: "Route running, quickness, special teams", comparison: "Ceiling: Russell Gage, Floor: Practice squad" },
    { rank: 223, name: "Andre Greene", position: "WR", school: "North Carolina", height: "6'3\"", weight: 210, grade: "5.50", tier: "Round 7", strengths: "Size, contested catches, project", comparison: "Ceiling: Miles Boykin, Floor: Practice squad" },
    { rank: 224, name: "Nathaniel Gilliam", position: "WR", school: "Pittsburgh", height: "5'10\"", weight: 185, grade: "5.48", tier: "Round 7", strengths: "Speed, quickness, slot potential", comparison: "Ceiling: Trent Taylor, Floor: Practice squad" },
    { rank: 225, name: "Kaden Davis", position: "WR", school: "Kansas State", height: "6'1\"", weight: 200, grade: "5.48", tier: "Round 7", strengths: "Route running, contested catches, development", comparison: "Ceiling: David Moore, Floor: Practice squad" },
    { rank: 226, name: "Samuel Patterson", position: "WR", school: "Washington", height: "6'2\"", weight: 205, grade: "5.45", tier: "Round 7", strengths: "Size, special teams, developmental", comparison: "Ceiling: Codey McElroy, Floor: Practice squad" },
    { rank: 227, name: "Tyrone Ellis", position: "WR", school: "Auburn", height: "5'11\"", weight: 190, grade: "5.45", tier: "Round 7", strengths: "Speed, return ability, project", comparison: "Ceiling: Marcus Johnson, Floor: Practice squad" },
    { rank: 228, name: "Cameron Scott", position: "WR", school: "South Carolina", height: "6'0\"", weight: 195, grade: "5.42", tier: "Round 7", strengths: "Route running, hands, possession", comparison: "Ceiling: Quez Watkins, Floor: Practice squad" },
    { rank: 229, name: "Devin Price", position: "WR", school: "Florida State", height: "6'3\"", weight: 210, grade: "5.42", tier: "Round 7", strengths: "Size, developmental, red zone potential", comparison: "Ceiling: Auden Tate, Floor: Practice squad" },
    { rank: 230, name: "Xavier Robinson", position: "WR", school: "Georgia", height: "6'0\"", weight: 195, grade: "5.40", tier: "Round 7", strengths: "Route running, quickness, development", comparison: "Ceiling: Trevor Davis, Floor: Practice squad" }
,
,
];

// ==========================================
// PFF POSITIONAL RANKINGS 2026
// ==========================================

const pffPositionalRankings = {
    QB: [
        { rank: 1, name: "Fernando Mendoza", school: "Indiana", overallRank: 4, grade: 90.0, oneLineSummary: "Accurate thrower with excellent size and elite ball placement. Franchise QB material." },
        { rank: 2, name: "Ty Simpson", school: "Alabama", overallRank: 24, grade: 88.0, oneLineSummary: "Sound mechanics and accuracy with quick feet but limited starting experience." },
        { rank: 3, name: "Trinidad Chambliss", school: "Ole Miss", overallRank: 77, grade: 85.0, oneLineSummary: "Accurate with excellent leadership but size concerns for some scouts." },
        { rank: 4, name: "Carson Beck", school: "Miami", overallRank: 91, grade: 84.0, oneLineSummary: "Physical tools have never been the question. Needs consistency." }
   ,
        { rank: 5, name: "Will Rogers", school: "Washington", overallRank: 156, grade: 55.2, oneLineSummary: "Accurate thrower with quick release and anticipation." },
        { rank: 6, name: "Maalik Murphy", school: "Duke", overallRank: 157, grade: 55.2, oneLineSummary: "Big-armed prospect with size and developmental upside." },
        { rank: 7, name: "Brady Cook", school: "Missouri", overallRank: 158, grade: 55.8, oneLineSummary: "Athletic leader with dual-threat ability and toughness." },
        { rank: 8, name: "Jordan McCloud", school: "Texas State", overallRank: 159, grade: 55.8, oneLineSummary: "Accurate passer with mobility and solid production." },
        { rank: 9, name: "Kyle McCord", school: "Syracuse", overallRank: 160, grade: 55.8, oneLineSummary: "Pocket presence with arm strength and anticipation." },
        { rank: 10, name: "Conner Weigman", school: "Texas A&M", overallRank: 161, grade: 55.5, oneLineSummary: "Arm talent with poise and pocket awareness." },
        { rank: 11, name: "Brock Vandagriff", school: "Georgia", overallRank: 162, grade: 55.5, oneLineSummary: "Strong-armed athlete with upside and size." },
        { rank: 12, name: "Miller Moss", school: "Louisville", overallRank: 163, grade: 55.2, oneLineSummary: "Accurate processor with anticipation and timing." },
        { rank: 13, name: "Tyler Van Dyke", school: "Wisconsin", overallRank: 164, grade: 55.0, oneLineSummary: "Pro-style QB with size and big arm." },
        { rank: 14, name: "Hayden Wolff", school: "Western Kentucky", overallRank: 165, grade: 55.0, oneLineSummary: "Size prospect with pocket presence and leadership." },
        { rank: 15, name: "Grayson McCall", school: "NC State", overallRank: 166, grade: 54.8, oneLineSummary: "Efficient thrower with accuracy and decision-making." },
        { rank: 16, name: "Chevan Cordeiro", school: "San Jose State", overallRank: 167, grade: 54.8, oneLineSummary: "Mobile playmaker with leadership and improvisation." },
        { rank: 17, name: "Avery Johnson", school: "Kansas State", overallRank: 168, grade: 54.5, oneLineSummary: "Athletic dual-threat with arm talent and upside." },
        { rank: 18, name: "Khalib Johnson", school: "Eastern Michigan", overallRank: 169, grade: 54.5, oneLineSummary: "Size prospect with arm strength and potential." },
        { rank: 19, name: "John Mateer", school: "Washington State", overallRank: 170, grade: 54.2, oneLineSummary: "Tough runner with athleticism and competitiveness." },
        { rank: 20, name: "Jalen Milroe", school: "Alabama", overallRank: 171, grade: 54.0, oneLineSummary: "Elite athlete with arm strength and development needed." },
        { rank: 21, name: "LaNorris Sellers", school: "South Carolina", overallRank: 172, grade: 54.0, oneLineSummary: "Dual-threat with arm strength and leadership." },
        { rank: 22, name: "Dante Reno", school: "Boston College", overallRank: 173, grade: 53.8, oneLineSummary: "Size prospect with accuracy and pocket presence." },
        { rank: 23, name: "Tavien St. Clair", school: "Ohio State", overallRank: 174, grade: 53.8, oneLineSummary: "Strong-armed pro-style QB with size." },
        { rank: 24, name: "Jack Larsen", school: "NC State", overallRank: 175, grade: 53.5, oneLineSummary: "Consistent leader with accuracy and football IQ." },
        { rank: 25, name: "Cade Klubnik", school: "Clemson", overallRank: 176, grade: 53.5, oneLineSummary: "Athletic talent with arm strength and upside." },
        { rank: 26, name: "Devin Brown", school: "Oklahoma", overallRank: 177, grade: 53.5, oneLineSummary: "Strong-armed prospect with size and potential." },
        { rank: 27, name: "Garrett Greene", school: "West Virginia", overallRank: 178, grade: 53.2, oneLineSummary: "Athletic playmaker with dual-threat ability." },
        { rank: 28, name: "Preston Stone", school: "Tulsa", overallRank: 179, grade: 53.0, oneLineSummary: "Smart processor with accuracy and pocket presence." },
        { rank: 29, name: "Tyler Shough", school: "Louisville", overallRank: 180, grade: 53.0, oneLineSummary: "Experienced pro-style QB with size and maturity." }],
    RB: [
        { rank: 1, name: "Jeremiyah Love", school: "Notre Dame", overallRank: 9, grade: 91.5, oneLineSummary: "Reggie Bush-like dynamo with vision, burst, and elite receiving ability." },
        { rank: 2, name: "Jadarian Price", school: "Notre Dame", overallRank: 56, grade: 86.5, oneLineSummary: "Compact runner with terrific vision and elite kick return ability." },
        { rank: 3, name: "Emmett Johnson", school: "Nebraska", overallRank: 84, grade: 85.0, oneLineSummary: "Special lateral agility with elite vision and patience." },
        { rank: 4, name: "Jonah Coleman", school: "Washington", overallRank: 81, grade: 85.5, oneLineSummary: "Three-down back despite limited athleticism. Reliable in pass pro." },
        { rank: 5, name: "Nicholas Singleton", school: "Penn State", overallRank: 96, grade: 83.5, oneLineSummary: "Explosive blend of power and speed with home run potential." }
   ,
        { rank: 6, name: "Kaleb Johnson", school: "Iowa", overallRank: 181, grade: 58.0, oneLineSummary: "Powerful runner with vision and physicality." },
        { rank: 7, name: "Kalel Mullings", school: "Michigan", overallRank: 182, grade: 57.8, oneLineSummary: "Big downhill runner with power and production." },
        { rank: 8, name: "Trevor Etienne", school: "Georgia", overallRank: 183, grade: 57.5, oneLineSummary: "Explosive back with speed and receiving ability." },
        { rank: 9, name: "Donovan Edwards", school: "Michigan", overallRank: 184, grade: 57.2, oneLineSummary: "Speed back with versatility and receiving skills." },
        { rank: 10, name: "Tahj Brooks", school: "Texas Tech", overallRank: 185, grade: 57.0, oneLineSummary: "Big, powerful runner with durability." },
        { rank: 11, name: "Ulysses Bentley", school: "Ole Miss", overallRank: 186, grade: 56.8, oneLineSummary: "Quick, elusive back with receiving ability." },
        { rank: 12, name: "Kye Robichaux", school: "Baylor", overallRank: 187, grade: 56.8, oneLineSummary: "Patient runner with vision and power." },
        { rank: 13, name: "Damien Martinez", school: "Texas A&M", overallRank: 188, grade: 56.5, oneLineSummary: "Physical back with youth and upside." },
        { rank: 14, name: "Cam Skattebo", school: "Arizona State", overallRank: 189, grade: 56.5, oneLineSummary: "Versatile power back with toughness." },
        { rank: 15, name: "Branson Robinson", school: "Georgia", overallRank: 190, grade: 56.2, oneLineSummary: "Explosive power back with limited reps." },
        { rank: 16, name: "Phil Mafah", school: "Clemson", overallRank: 191, grade: 56.2, oneLineSummary: "Big, durable runner with power." },
        { rank: 17, name: "RJ Harvey", school: "UCF", overallRank: 192, grade: 56.0, oneLineSummary: "Speed back with big play ability." },
        { rank: 18, name: "Le'Veon Moss", school: "Texas A&M", overallRank: 193, grade: 55.8, oneLineSummary: "Three-down back with pass protection skills." },
        { rank: 19, name: "Jarquez Hunter", school: "Auburn", overallRank: 194, grade: 55.5, oneLineSummary: "Quick SEC back with return ability." },
        { rank: 20, name: "Kaelon Black", school: "Army", overallRank: 195, grade: 55.2, oneLineSummary: "Intelligent back with scheme versatility." },
        { rank: 21, name: "Jalen White", school: "Georgia Southern", overallRank: 196, grade: 55.0, oneLineSummary: "Fast Sun Belt back with receiving skills." }],
    WR: [
        { rank: 1, name: "Carnell Tate", school: "Ohio State", overallRank: 7, grade: 92.0, oneLineSummary: "Tall, long wideout who attacks leverage and tracks ball beautifully." },
        { rank: 2, name: "Jordyn Tyson", school: "Arizona State", overallRank: 10, grade: 90.0, oneLineSummary: "Explosive receiver who wins on 50/50 balls. Uncoverable in red zone." },
        { rank: 3, name: "Makai Lemon", school: "USC", overallRank: 12, grade: 89.5, oneLineSummary: "Warrior with RB body and elite slot ability." },
        { rank: 4, name: "Zachariah Branch", school: "Georgia", overallRank: 23, grade: 87.0, oneLineSummary: "Lightning quick with track speed. Dynamic after catch." },
        { rank: 5, name: "Denzel Boston", school: "Washington", overallRank: 20, grade: 86.5, oneLineSummary: "Big-framed wideout with exceptional ball skills." }
   ,
        { rank: 6, name: "Tez Johnson", school: "Oregon", overallRank: 197, grade: 58.8, oneLineSummary: "Speedy, quick route runner with separation ability." },
        { rank: 7, name: "Xavier Restrepo", school: "Miami", overallRank: 198, grade: 58.5, oneLineSummary: "Quick slot receiver with return skills." },
        { rank: 8, name: "Elic Ayomanor", school: "Stanford", overallRank: 199, grade: 58.5, oneLineSummary: "Big, physical wideout who wins contested catches." },
        { rank: 9, name: "Luther Burden", school: "Georgia", overallRank: 200, grade: 58.2, oneLineSummary: "Versatile weapon with YAC ability and toughness." },
        { rank: 10, name: "Kyle Williams", school: "Washington State", overallRank: 201, grade: 58.0, oneLineSummary: "Speedy deep threat with route running skills." },
        { rank: 11, name: "Barion Brown", school: "Kentucky", overallRank: 202, grade: 57.8, oneLineSummary: "Size/speed combo with contested catch ability." },
        { rank: 12, name: "Jack Bech", school: "TCU", overallRank: 203, grade: 57.8, oneLineSummary: "Big red zone threat with reliable hands." },
        { rank: 13, name: "Jalen Royals", school: "Utah State", overallRank: 204, grade: 57.5, oneLineSummary: "Route technician with contested catch ability." },
        { rank: 14, name: "Tre Harris", school: "Ole Miss", overallRank: 205, grade: 57.5, oneLineSummary: "Physical big target with red zone skills." },
        { rank: 15, name: "Pat Bryant", school: "Florida State", overallRank: 206, grade: 57.2, oneLineSummary: "Developing big receiver with contested catch upside." },
        { rank: 16, name: "Tahj Washington", school: "USC", overallRank: 207, grade: 57.2, oneLineSummary: "Speedy slot option with return ability." },
        { rank: 17, name: "Will Sheppard", school: "Colorado", overallRank: 208, grade: 57.0, oneLineSummary: "Big, physical receiver who wins 50/50 balls." },
        { rank: 18, name: "Isaac TeSlaa", school: "Arkansas", overallRank: 209, grade: 56.8, oneLineSummary: "Tall red zone target with development upside." },
        { rank: 19, name: "Montrell Johnson", school: "Florida", overallRank: 210, grade: 56.8, oneLineSummary: "Athletic receiver with contested catch skills." },
        { rank: 20, name: "Dante Wright", school: "Colorado", overallRank: 211, grade: 56.5, oneLineSummary: "Speedy, versatile receiver with quickness." },
        { rank: 21, name: "Lonnie Galloway", school: "West Virginia", overallRank: 212, grade: 56.5, oneLineSummary: "Reliable route runner with good hands." },
        { rank: 22, name: "Evan Prater", school: "Cincinnati", overallRank: 213, grade: 56.2, oneLineSummary: "Athletic YAC specialist with upside." },
        { rank: 23, name: "Marcus Rosemy-Jacksaint", school: "Georgia", overallRank: 214, grade: 56.2, oneLineSummary: "Blocking specialist with size and contested catch ability." },
        { rank: 24, name: "Kris Mitchell", school: "Miami", overallRank: 215, grade: 56.0, oneLineSummary: "Red zone target with size and contested catch skills." },
        { rank: 25, name: "Connor Gibson", school: "Texas", overallRank: 216, grade: 55.8, oneLineSummary: "Physical developmental prospect with size." },
        { rank: 26, name: "Jordan Moore", school: "Texas A&M", overallRank: 217, grade: 55.8, oneLineSummary: "Possession receiver with route running and hands." },
        { rank: 27, name: "TreShawn Holden", school: "Oregon", overallRank: 218, grade: 55.5, oneLineSummary: "Size prospect with contested catch upside." },
        { rank: 28, name: "Jabari Camper", school: "Louisville", overallRank: 219, grade: 55.5, oneLineSummary: "Tall red zone project with developmental traits." },
        { rank: 29, name: "Marcus Alexander", school: "NC State", overallRank: 220, grade: 55.2, oneLineSummary: "Speedy return specialist with special teams value." },
        { rank: 30, name: "Christian Lewis", school: "Alabama", overallRank: 221, grade: 55.2, oneLineSummary: "Blocking specialist with size and developmental traits." },
        { rank: 31, name: "Elijah Banks", school: "Ole Miss", overallRank: 222, grade: 55.0, oneLineSummary: "Route runner with special teams value." },
        { rank: 32, name: "Andre Greene", school: "North Carolina", overallRank: 223, grade: 55.0, oneLineSummary: "Contested catch project with size and upside." },
        { rank: 33, name: "Nathaniel Gilliam", school: "Pittsburgh", overallRank: 224, grade: 54.8, oneLineSummary: "Speedy slot prospect with quickness." },
        { rank: 34, name: "Kaden Davis", school: "Kansas State", overallRank: 225, grade: 54.8, oneLineSummary: "Route runner with contested catch ability." },
        { rank: 35, name: "Samuel Patterson", school: "Washington", overallRank: 226, grade: 54.5, oneLineSummary: "Size prospect with special teams potential." },
        { rank: 36, name: "Tyrone Ellis", school: "Auburn", overallRank: 227, grade: 54.5, oneLineSummary: "Speedy return specialist with developmental traits." },
        { rank: 37, name: "Cameron Scott", school: "South Carolina", overallRank: 228, grade: 54.2, oneLineSummary: "Possession receiver with route running skills." },
        { rank: 38, name: "Devin Price", school: "Florida State", overallRank: 229, grade: 54.2, oneLineSummary: "Red zone project with size and developmental upside." },
        { rank: 39, name: "Xavier Robinson", school: "Georgia", overallRank: 230, grade: 54.0, oneLineSummary: "Quick route runner with developmental upside." }],
    TE: [
        { rank: 1, name: "Kenyon Sadiq", school: "Oregon", overallRank: 17, grade: 88.0, oneLineSummary: "Versatile explosive weapon for modern NFL." },
        { rank: 2, name: "Max Klare", school: "Ohio State", overallRank: 63, grade: 85.5, oneLineSummary: "Natural receiving gifts with blocking limitations." },
        { rank: 3, name: "Eli Stowers", school: "Vanderbilt", overallRank: 74, grade: 85.0, oneLineSummary: "Former QB with elite athleticism. Movable chess piece." },
        { rank: 4, name: "Jack Endries", school: "Texas", overallRank: 97, grade: 83.0, oneLineSummary: "Fundamentally sound receiver who gets open." },
        { rank: 5, name: "Michael Trigg", school: "Baylor", overallRank: 82, grade: 82.5, oneLineSummary: "Weapon between the numbers with mismatch size." }
    ],
    OT: [
        { rank: 1, name: "Francis Mauigoa", school: "Miami", overallRank: 6, grade: 90.0, oneLineSummary: "True mauler who destroys pass rushers at POA." },
        { rank: 2, name: "Spencer Fano", school: "Utah", overallRank: 8, grade: 89.0, oneLineSummary: "Technically sound with good punch. Ideal zone fit." },
        { rank: 3, name: "Caleb Lomu", school: "Utah", overallRank: 21, grade: 87.5, oneLineSummary: "Agile bookend with franchise LT upside." },
        { rank: 4, name: "Kadyn Proctor", school: "Alabama", overallRank: 27, grade: 85.0, oneLineSummary: "Rare combination of mass and movement." },
        { rank: 5, name: "Monroe Freeling", school: "Georgia", overallRank: 32, grade: 84.5, oneLineSummary: "Ideal size and bend with starting LT ability." }
    ],
    IOL: [
        { rank: 1, name: "Olaivavega Ioane", school: "Penn State", overallRank: 18, grade: 88.5, oneLineSummary: "Dominant LG with strength and agility." },
        { rank: 2, name: "Connor Lew", school: "Auburn", overallRank: 60, grade: 87.0, oneLineSummary: "Center with exceptional movement skills." },
        { rank: 3, name: "Emmanuel Pregnon", school: "Oregon", overallRank: 36, grade: 86.0, oneLineSummary: "Day-one contributor with power and technique." },
        { rank: 4, name: "Chase Bisontis", school: "Texas A&M", overallRank: 61, grade: 85.0, oneLineSummary: "Thick, powerful guard with run-blocking temperament." },
        { rank: 5, name: "Jake Slaughter", school: "Florida", overallRank: 83, grade: 84.0, oneLineSummary: "Center with blend of intellect and physicality." }
    ],
    EDGE: [
        { rank: 1, name: "Rueben Bain Jr.", school: "Miami", overallRank: 2, grade: 93.0, oneLineSummary: "Thick, powerful edge with violent hands and non-stop motor." },
        { rank: 2, name: "David Bailey", school: "Texas Tech", overallRank: 5, grade: 92.0, oneLineSummary: "Ultra-explosive with elite production and get-off." },
        { rank: 3, name: "Akheem Mesidor", school: "Miami", overallRank: 31, grade: 89.5, oneLineSummary: "Ideal frame with relentless motor and power rush." },
        { rank: 4, name: "Keldric Faulk", school: "Auburn", overallRank: 15, grade: 89.0, oneLineSummary: "Perfect 4-3 DE frame with powerful hands." },
        { rank: 5, name: "Cashius Howell", school: "Texas A&M", overallRank: 25, grade: 87.5, oneLineSummary: "Speed rush, bend, and motor." }
    ],
    DL: [
        { rank: 1, name: "Peter Woods", school: "Clemson", overallRank: 16, grade: 87.5, oneLineSummary: "First-step quickness with scheme versatility." },
        { rank: 2, name: "Kayden McDonald", school: "Ohio State", overallRank: 19, grade: 87.0, oneLineSummary: "Big Ten DL of the Year with strength and quickness." },
        { rank: 3, name: "Caleb Banks", school: "Florida", overallRank: 29, grade: 85.5, oneLineSummary: "Tall, long athlete with twitch in hands." },
        { rank: 4, name: "Lee Hunter", school: "Texas Tech", overallRank: 37, grade: 85.0, oneLineSummary: "Massive run-stuffer who demands double teams." },
        { rank: 5, name: "Christen Miller", school: "Georgia", overallRank: 42, grade: 84.0, oneLineSummary: "Disruptive 3-technique with violent hands." }
    ],
    LB: [
        { rank: 1, name: "Arvell Reese", school: "Ohio State", overallRank: 1, grade: 92.0, oneLineSummary: "Complete player with elite burst and pass-rush ability." },
        { rank: 2, name: "Sonny Styles", school: "Ohio State", overallRank: 13, grade: 90.0, oneLineSummary: "Former safety with LB size and elite speed." },
        { rank: 3, name: "CJ Allen", school: "Georgia", overallRank: 22, grade: 87.0, oneLineSummary: "Three-down LB with excellent read-react skills." },
        { rank: 4, name: "Anthony Hill Jr.", school: "Texas", overallRank: 35, grade: 86.0, oneLineSummary: "Modern LB built for speed and versatility." },
        { rank: 5, name: "Jake Golday", school: "Cincinnati", overallRank: 51, grade: 85.0, oneLineSummary: "Speed-based LB with fantastic lateral range." }
    ],
    CB: [
        { rank: 1, name: "Mansoor Delane", school: "LSU", overallRank: 11, grade: 89.0, oneLineSummary: "Most instinctive CB in class with elite ball skills." },
        { rank: 2, name: "Jermod McCoy", school: "Tennessee", overallRank: 14, grade: 88.5, oneLineSummary: "Scheme versatile with ball-hawking traits." },
        { rank: 3, name: "Avieon Terrell", school: "Clemson", overallRank: 26, grade: 87.0, oneLineSummary: "Elite ball skills and fluid athleticism." },
        { rank: 4, name: "Brandon Cisse", school: "South Carolina", overallRank: 30, grade: 86.5, oneLineSummary: "Twitchy cover corner with elite 4.35 speed." },
        { rank: 5, name: "Colton Hood", school: "Tennessee", overallRank: 33, grade: 86.0, oneLineSummary: "Complete player with 4.4 speed and production." }
    ],
    S: [
        { rank: 1, name: "Caleb Downs", school: "Ohio State", overallRank: 3, grade: 92.0, oneLineSummary: "Defensive coordinator on the field with elite instincts." },
        { rank: 2, name: "Emmanuel McNeil-Warren", school: "Toledo", overallRank: 34, grade: 87.5, oneLineSummary: "Versatile playmaker who can play free or box." },
        { rank: 3, name: "Dillon Thieneman", school: "Oregon", overallRank: 38, grade: 87.0, oneLineSummary: "Tall, long safety with fantastic production." },
        { rank: 4, name: "A.J. Haulcy", school: "LSU", overallRank: 50, grade: 85.0, oneLineSummary: "Physical box safety with good instincts." },
        { rank: 5, name: "Kamari Ramsey", school: "USC", overallRank: 57, grade: 84.5, oneLineSummary: "Coverage instincts border on exceptional." }
    ]
};

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { pffBigBoardData, pffPositionalRankings };
}
