const fs=require('fs'),vm=require('vm'),assert=require('assert');
class Node{
 constructor(tag='div',text=''){this.tag=tag;this._text=text;this.children=[];this.attrs={};this.events={};this.style={};this.value='';this.hidden=false;this.open=false;this.isConnected=true;this.classList={toggle(){}}}
 set textContent(v){this._text=String(v??'');this.children=[]}get textContent(){return this._text+this.children.map(n=>typeof n==='string'?n:n.textContent).join('')}
 append(...nodes){this.children.push(...nodes)}replaceChildren(...nodes){this._text='';this.children=nodes}setAttribute(k,v){this.attrs[k]=v}addEventListener(k,v){this.events[k]=v}add(n){this.append(n)}showModal(){this.open=true}close(){this.open=false}matches(){return false}contains(){return false}scrollIntoView(){}remove(){}getBoundingClientRect(){return {left:100,right:250,top:100}}}
const nodes={},get=id=>nodes[id]??=new Node();get('group').value='top';get('sort').value='source';const document={getElementById:get,createElement:tag=>new Node(tag),createTextNode:t=>t,addEventListener(){}};
const ctx={document,window:{addEventListener(){}},localStorage:{getItem:()=>null,setItem(){}},Date,Set,Map,Option:function(t,v){const n=new Node('option',t);n.value=v;return n},setTimeout:()=>1,clearTimeout(){},setInterval(){},fetch:()=>new Promise(()=>{}),AbortSignal:{timeout:()=>null},innerWidth:1200,innerHeight:800};
vm.createContext(ctx);const root=__dirname+'/';const html=fs.readFileSync(root+'index.html','utf8');vm.runInContext(fs.readFileSync(root+'features.js','utf8'),ctx);vm.runInContext(html.split('<script>')[1].split('</script>')[0],ctx);
const data=JSON.parse(fs.readFileSync(root+'players.json'));ctx.apply(data);assert.equal(get('rows').children.length,100);
assert.equal(ctx.sourceAge({editorial_date:'2026-09-01'},new Date('2026-09-15T08:00:00Z')),14);assert.equal(ctx.sourceAge({},new Date()),null);assert.equal(ctx.sourceAge({editorial_date:'2999-01-01'},new Date()),null);
assert.equal(ctx.rankSpread({source_ranks:{a:1,b:90}}),89);assert.equal(ctx.disagreement({source_ranks:{a:1,b:90}}),'Limited coverage');assert.equal(ctx.disagreement({source_ranks:{a:1,b:41,c:10}}),'Wide disagreement');assert.equal(ctx.rankSpread({source_ranks:{a:5}}),null);
for(let i=0;i<4;i++)assert(ctx.toggleCompare(data.players[i].id));assert.equal(ctx.toggleCompare(data.players[4].id),false);assert.equal(get('compareCount').textContent,'4/4 selected');ctx.openComparison();assert(get('comparison').open);for(let i=0;i<4;i++)assert(get('comparisonContent').textContent.includes(data.players[i].name));
get('search').value='no such player';ctx.render();assert.equal(get('compareCount').textContent,'4/4 selected');assert.equal(get('rows').children.length,1);
get('search').value='';get('group').value='all';get('disagreement').value='wide';ctx.render();const expected=data.players.filter(p=>ctx.disagreement(p)==='Wide disagreement').length;assert.equal(get('rows').children.length,expected);
get('clearCompare').onclick();assert.equal(get('compareCount').textContent,'0/4 selected');assert(get('openCompare').disabled);assert(get('comparisonContent').textContent.includes('at least two'));
vm.runInContext("personal[players[0].id]={notes:'User film note',rank:9}",ctx);ctx.toggleCompare(data.players[0].id);ctx.toggleCompare(data.players[1].id);ctx.renderComparison();assert(get('comparisonContent').textContent.includes('User film note'));assert(get('comparisonContent').textContent.includes('#9'));
console.log('PASS: full page render, date boundaries, missing-date handling, disagreement math/filter, selection limit, cross-filter retention, comparisons and personal notes.');
get('disagreement').value='';ctx.openProfile(data.players[0]);get('myTier').value='2';get('needsFilm').checked=true;get('notes').value='Film reviewed';get('save').onclick();
assert.equal(vm.runInContext('own(players[0].id).tier',ctx),'2');assert.equal(vm.runInContext('own(players[0].id).rank',ctx),9);
get('tierFilter').value='2';ctx.render();assert.equal(get('rows').children.length,1);assert(get('rows').textContent.includes('My tier 2'));
get('tierFilter').value='';get('filmFilter').onclick();assert.equal(get('rows').children.length,1);get('filmFilter').onclick();assert.equal(get('rows').children.length,125);
ctx.renderHistory({...data.players[0],history:[{recorded_at:'2026-09-14T12:00:00Z',rank:3,source_ranks:{sg:4}}]});assert(get('rankHistory').textContent.includes('Baseline recorded'));assert(get('rankHistory').textContent.includes('#3'));
(async()=>{get('file').files=[{size:100,text:async()=>JSON.stringify({version:1,year:2027,personal:{[data.players[0].id]:{notes:'Restored',tier:'3',film:true}}})}];await get('file').onchange();assert.equal(vm.runInContext('own(players[0].id).tier',ctx),'3');assert.equal(vm.runInContext('own(players[0].id).film',ctx),true);
get('file').files=[{size:100,text:async()=>JSON.stringify({version:1,year:2027,personal:{[data.players[0].id]:{notes:'Legacy'}}})}];await get('file').onchange();assert.equal(vm.runInContext('own(players[0].id).tier',ctx),'3');assert.equal(vm.runInContext('own(players[0].id).film',ctx),true);console.log('PASS: tier and film saves/filters, rank preservation, baseline history and modern/legacy backup restoration.');})().catch(e=>{console.error(e);process.exitCode=1});
